export type SFStatus = 'done' | 'in-progress' | 'todo';
export interface Sf { id: string; title: string; status: SFStatus; }

export const SOFTWARE_FACTORIES: Sf[] = [
  { id: 'SF-00',  title: 'Bootstrap & Meta-Factory', status: 'done' },
  { id: 'SF-01',  title: 'Discovery / Onboarding', status: 'done' },
  { id: 'SF-02',  title: 'Founder Interview', status: 'done' },
  { id: 'SF-03',  title: 'Idea Refinement', status: 'done' },
  { id: 'SF-04',  title: 'Market Research', status: 'in-progress' },
  { id: 'SF-05',  title: 'Competitive Intelligence', status: 'todo' },
  { id: 'SF-06',  title: 'Business Model Canvas', status: 'todo' },
  { id: 'SF-07',  title: 'Value Proposition', status: 'todo' },
  { id: 'SF-08',  title: 'ICP + Personas', status: 'todo' },
  { id: 'SF-09',  title: 'Pricing Strategy', status: 'todo' },
  { id: 'SF-10',  title: 'GTM Plan', status: 'todo' },
  { id: 'SF-11',  title: 'Startup Package', status: 'in-progress' },
  { id: 'SF-12',  title: 'Business Proposal', status: 'done' },
  { id: 'SF-13',  title: 'Information Architecture', status: 'done' },
  { id: 'SF-14',  title: 'Landing Page Generator', status: 'done' },
  { id: 'SF-15',  title: 'MVP Scope', status: 'done' },
  { id: 'SF-16',  title: 'Initiative → Epic → Story Breakdown', status: 'done' },
  { id: 'SF-17',  title: 'Design System Picker', status: 'done' },
  { id: 'SF-18',  title: 'Style Guide & Theme', status: 'done' },
  { id: 'SF-19',  title: 'Click-through Prototype', status: 'done' },
  { id: 'SF-20',  title: 'Responsive Preview', status: 'done' },
  { id: 'SF-21',  title: 'Design→Code (Figma)', status: 'todo' },
  { id: 'SF-22',  title: 'Code Scaffolding', status: 'todo' },
  { id: 'SF-23',  title: 'Component Library', status: 'todo' },
  { id: 'SF-24',  title: 'Data Modeling', status: 'todo' },
  { id: 'SF-25',  title: 'API Contract', status: 'todo' },
  { id: 'SF-26',  title: 'Backend Scaffolding', status: 'todo' },
  { id: 'SF-27',  title: 'Auth & Session', status: 'in-progress' },
  { id: 'SF-28',  title: 'Payments Integration', status: 'todo' },
  { id: 'SF-29',  title: 'Email / Notifications', status: 'todo' },
  { id: 'SF-30',  title: 'Analytics Instrumentation', status: 'todo' },
  { id: 'SF-31',  title: 'Feature Flags', status: 'todo' },
  { id: 'SF-32',  title: 'A/B Testing', status: 'in-progress' },
  { id: 'SF-33',  title: 'Search & Discovery', status: 'todo' },
  { id: 'SF-34',  title: 'File Storage', status: 'todo' },
  { id: 'SF-35',  title: 'Media Pipeline', status: 'todo' },
  { id: 'SF-36',  title: 'Realtime & Chat', status: 'todo' },
  { id: 'SF-37',  title: 'Push Notifications', status: 'todo' },
  { id: 'SF-38',  title: 'Background Jobs', status: 'todo' },
  { id: 'SF-39',  title: 'Cron / Scheduler', status: 'todo' },
  { id: 'SF-40',  title: 'Rate Limiting', status: 'todo' },
  { id: 'SF-41',  title: 'Idempotency Layer', status: 'todo' },
  { id: 'SF-42',  title: 'Observability (Traces/Logs)', status: 'in-progress' },
  { id: 'SF-43',  title: 'Metrics & Dashboards', status: 'todo' },
  { id: 'SF-44',  title: 'Error Tracking', status: 'todo' },
  { id: 'SF-45',  title: 'Uptime & Synthetic Checks', status: 'todo' },
  { id: 'SF-46',  title: 'Alerts & On-call', status: 'todo' },
  { id: 'SF-47',  title: 'Incident Runbook', status: 'todo' },
  { id: 'SF-48',  title: 'Postmortem Templates', status: 'todo' },
  { id: 'SF-49',  title: 'Security Scanning', status: 'in-progress' },
  { id: 'SF-50',  title: 'Secrets Management', status: 'done' },
  { id: 'SF-51',  title: 'IAM / RBAC', status: 'todo' },
  { id: 'SF-52',  title: 'Audit Log', status: 'todo' },
  { id: 'SF-53',  title: 'Compliance (SOC2/GDPR)', status: 'todo' },
  { id: 'SF-54',  title: 'Legal Templates', status: 'in-progress' },
  { id: 'SF-55',  title: 'Terms & Privacy Generator', status: 'in-progress' },
  { id: 'SF-56',  title: 'Cookie & Consent', status: 'in-progress' },
  { id: 'SF-57',  title: 'Localisation (i18n)', status: 'todo' },
  { id: 'SF-58',  title: 'Accessibility (a11y) Gate', status: 'todo' },
  { id: 'SF-59',  title: 'Performance Budget', status: 'todo' },
  { id: 'SF-60',  title: 'Web Vitals & Lighthouse', status: 'todo' },
  { id: 'SF-61',  title: 'SEO Foundation', status: 'in-progress' },
  { id: 'SF-62',  title: 'Sitemap & Robots', status: 'todo' },
  { id: 'SF-63',  title: 'Structured Data', status: 'in-progress' },
  { id: 'SF-64',  title: 'Social Meta / OG Cards', status: 'in-progress' },
  { id: 'SF-65',  title: 'Analytics Attribution', status: 'todo' },
  { id: 'SF-66',  title: 'CRM Integration', status: 'todo' },
  { id: 'SF-67',  title: 'Customer Support Portal', status: 'todo' },
  { id: 'SF-68',  title: 'Knowledge Base Generator', status: 'todo' },
  { id: 'SF-69',  title: 'Onboarding Emails', status: 'todo' },
  { id: 'SF-70',  title: 'Lifecycle Emails', status: 'todo' },
  { id: 'SF-71',  title: 'Segmentation', status: 'todo' },
  { id: 'SF-72',  title: 'Referrals & Invites', status: 'in-progress' },
  { id: 'SF-73',  title: 'Waitlist / Beta', status: 'todo' },
  { id: 'SF-74',  title: 'Feedback Widget', status: 'in-progress' },
  { id: 'SF-75',  title: 'In-app Announcements', status: 'todo' },
  { id: 'SF-76',  title: 'NPS / Surveys', status: 'todo' },
  { id: 'SF-77',  title: 'A/B Winner Rollout', status: 'todo' },
  { id: 'SF-78',  title: 'Data Warehouse', status: 'todo' },
  { id: 'SF-79',  title: 'ETL / ELT Pipelines', status: 'todo' },
  { id: 'SF-80',  title: 'Reverse ETL (CDP)', status: 'todo' },
  { id: 'SF-81',  title: 'ML Feature Store', status: 'todo' },
  { id: 'SF-82',  title: 'Prompt Registry', status: 'todo' },
  { id: 'SF-83',  title: 'LLM Evals', status: 'todo' },
  { id: 'SF-84',  title: 'Content Moderation', status: 'todo' },
  { id: 'SF-85',  title: 'Vector DB', status: 'todo' },
  { id: 'SF-86',  title: 'RAG Pipeline', status: 'todo' },
  { id: 'SF-87',  title: 'Voice / Speech', status: 'in-progress' },
  { id: 'SF-88',  title: 'Vision / Image', status: 'todo' },
  { id: 'SF-89',  title: 'Recommendation Engine', status: 'todo' },
  { id: 'SF-90',  title: 'Personalisation', status: 'todo' },
  { id: 'SF-91',  title: 'Autonomous Executor', status: 'in-progress' },
  { id: 'SF-92',  title: 'Multi-agent Orchestration', status: 'todo' },
  { id: 'SF-93',  title: 'Agent Skill Marketplace', status: 'todo' },
  { id: 'SF-94',  title: 'Human-in-the-loop Gate', status: 'todo' },
  { id: 'SF-95',  title: 'Cost Ledger', status: 'todo' },
  { id: 'SF-96',  title: 'Token Budget Enforcer', status: 'in-progress' },
  { id: 'SF-97',  title: 'Rate-limit Router', status: 'todo' },
  { id: 'SF-98',  title: 'Model Choice Router', status: 'done' },
  { id: 'SF-99',  title: 'BYOK Key Vault', status: 'todo' },
  { id: 'SF-100', title: 'Tenant Provisioning', status: 'todo' },
  { id: 'SF-101', title: 'Tenant Isolation', status: 'todo' },
  { id: 'SF-102', title: 'Blue/Green Deploys', status: 'todo' },
  { id: 'SF-103', title: 'Canary Deploys', status: 'todo' },
  { id: 'SF-104', title: 'Rollback Automation', status: 'todo' },
  { id: 'SF-105', title: 'DoD Gate', status: 'done' },
  { id: 'SF-106', title: 'Design ↔ Code Diff', status: 'todo' },
  { id: 'SF-107', title: 'Visual Regression Gate', status: 'todo' },
  { id: 'SF-108', title: 'Contract Testing', status: 'todo' },
  { id: 'SF-109', title: 'E2E Test Runner', status: 'todo' },
  { id: 'SF-110', title: 'Load / Perf Testing', status: 'todo' },
  { id: 'SF-111', title: 'Chaos Engineering', status: 'todo' },
  { id: 'SF-112', title: 'Backup & Restore', status: 'todo' },
  { id: 'SF-113', title: 'DR Runbook', status: 'todo' },
  { id: 'SF-114', title: 'Multi-region Failover', status: 'todo' },
  { id: 'SF-115', title: 'Cache Layer', status: 'todo' },
  { id: 'SF-116', title: 'CDN & Edge', status: 'todo' },
  { id: 'SF-117', title: 'Static Site Generator', status: 'todo' },
  { id: 'SF-118', title: 'Blog / CMS', status: 'in-progress' },
  { id: 'SF-119', title: 'Docs Site Generator', status: 'todo' },
  { id: 'SF-120', title: 'Investor Data Room', status: 'todo' },
  { id: 'SF-121', title: 'Fundraising CRM', status: 'todo' },
  { id: 'SF-122', title: 'Cap Table Manager', status: 'todo' },
  { id: 'SF-123', title: 'Hiring Pipeline', status: 'todo' },
  { id: 'SF-124', title: 'Applicant Tracking', status: 'todo' },
  { id: 'SF-125', title: 'Team Onboarding', status: 'in-progress' },
  { id: 'SF-126', title: 'Policy Docs Generator', status: 'todo' },
  { id: 'SF-127', title: 'Company Wiki', status: 'todo' },
  { id: 'SF-128', title: 'Sprint Planner', status: 'todo' },
  { id: 'SF-129', title: 'Standup Bot', status: 'todo' },
  { id: 'SF-130', title: 'Retrospective Tool', status: 'todo' },
  { id: 'SF-131', title: 'Roadmap Publisher', status: 'todo' },
  { id: 'SF-132', title: 'Changelog Generator', status: 'in-progress' },
  { id: 'SF-133', title: 'Release Notes', status: 'in-progress' },
  { id: 'SF-134', title: 'Status Page', status: 'todo' },
  { id: 'SF-135', title: 'Marketing Site', status: 'in-progress' },
  { id: 'SF-136', title: 'Pricing Page Generator', status: 'in-progress' },
  { id: 'SF-137', title: 'Sales Deck Generator', status: 'in-progress' },
  { id: 'SF-138', title: 'Contract & Quote Builder', status: 'todo' },
  { id: 'SF-139', title: 'Billing & Invoicing', status: 'todo' },
  { id: 'SF-140', title: 'Physical Tenant Provisioning', status: 'todo' },
];

export const CONTROL_PLANE: Sf[] = [
  { id: 'CP-01', title: 'Auth Broker', status: 'done' },
  { id: 'CP-02', title: 'Registry', status: 'done' },
  { id: 'CP-03', title: 'Workflow (Temporal)', status: 'done' },
  { id: 'CP-04', title: 'Event Bus', status: 'in-progress' },
  { id: 'CP-05', title: 'Policy Engine', status: 'todo' },
  { id: 'CP-06', title: 'Metering & Billing', status: 'todo' },
  { id: 'CP-07', title: 'Secrets (Vault)', status: 'done' },
  { id: 'CP-08', title: 'DoD Gate Service', status: 'done' },
  { id: 'CP-09', title: 'PR Lifecycle Guard', status: 'done' },
  { id: 'CP-10', title: 'Decision Registry', status: 'done' },
  { id: 'CP-11', title: 'Cost Ledger', status: 'todo' },
  { id: 'CP-12', title: 'Prompt Cache', status: 'in-progress' },
  { id: 'CP-13', title: 'Model Router', status: 'done' },
  { id: 'CP-14', title: 'Runaway Loop Guard', status: 'done' },
  { id: 'CP-15', title: 'Story Loop Runner', status: 'todo' },
  { id: 'CP-16', title: 'Dispatch Status', status: 'done' },
];

export function groupByStatus(items: Sf[]): Record<SFStatus, Sf[]> {
  const g: Record<SFStatus, Sf[]> = { done: [], 'in-progress': [], todo: [] };
  for (const it of items) g[it.status].push(it);
  return g;
}
