#!/bin/bash
# Pull all image-provider credentials from stolution vault into local .env
# Idempotent — safe to re-run at any time.
# Usage: bash scripts/pull-secrets.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"
STOLUTION="stolution"
VAULT_DIR="/home/s903/.vault"

log()  { printf '\033[0;36m[pull-secrets]\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[0;33m[pull-secrets] WARN:\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[0;31m[pull-secrets] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# ── Verify SSH connectivity ───────────────────────────────────────────────────
log "verifying SSH to $STOLUTION..."
ssh -o BatchMode=yes -o ConnectTimeout=5 "$STOLUTION" 'echo ok' > /dev/null 2>&1 || \
  fail "Cannot reach $STOLUTION via SSH. Check your VPN/connection."
log "SSH OK"

# ── Pull each service's credentials ──────────────────────────────────────────
log "reading vault files from $STOLUTION:$VAULT_DIR ..."

UNSPLASH_KEY=$(ssh "$STOLUTION" "awk -F= '/^UNSPLASH_ACCESS_KEY=/{print \$2}' $VAULT_DIR/image-provider-unsplash.env 2>/dev/null" || echo "")
PEXELS_KEY=$(ssh "$STOLUTION" "awk -F= '/^PEXELS_API_KEY=/{print \$2}' $VAULT_DIR/image-provider-pexels.env 2>/dev/null" || echo "")
FAL_KEY=$(ssh "$STOLUTION" "awk -F= '/^FAL_KEY=/{print \$2}' $VAULT_DIR/image-provider-fal.env 2>/dev/null" || echo "")
PIXABAY_KEY=$(ssh "$STOLUTION" "awk -F= '/^PIXABAY_API_KEY=/{print \$2}' $VAULT_DIR/image-provider-pixabay.env 2>/dev/null" || echo "")

CF_API_TOKEN=$(ssh "$STOLUTION" "awk -F= '/^CLOUDFLARE_API_TOKEN=/{print \$2}' $VAULT_DIR/image-provider-cloudflare-api-token.env 2>/dev/null" || echo "")
CF_ACCOUNT=$(ssh "$STOLUTION" "awk -F= '/^CLOUDFLARE_ACCOUNT_ID=/{print \$2}' $VAULT_DIR/image-provider-cloudflare-r2.env 2>/dev/null" || echo "")
R2_KEY_ID=$(ssh "$STOLUTION" "awk -F= '/^R2_ACCESS_KEY_ID=/{print \$2}' $VAULT_DIR/image-provider-cloudflare-r2.env 2>/dev/null" || echo "")
R2_SECRET=$(ssh "$STOLUTION" "awk -F= '/^R2_SECRET_ACCESS_KEY=/{print \$2}' $VAULT_DIR/image-provider-cloudflare-r2.env 2>/dev/null" || echo "")
R2_BUCKET=$(ssh "$STOLUTION" "awk -F= '/^R2_BUCKET=/{print \$2}' $VAULT_DIR/image-provider-cloudflare-r2.env 2>/dev/null" || echo "site-images")
R2_URL=$(ssh "$STOLUTION" "awk -F= '/^R2_PUBLIC_BASE_URL=/{print \$2}' $VAULT_DIR/image-provider-cloudflare-r2.env 2>/dev/null" || echo "")

# ── Report what was loaded (lengths only, no values) ─────────────────────────
[[ -n "$UNSPLASH_KEY"  ]] && log "unsplash: ${#UNSPLASH_KEY} chars"            || warn "unsplash: missing"
[[ -n "$PEXELS_KEY"    ]] && log "pexels:   ${#PEXELS_KEY} chars"              || warn "pexels: missing"
[[ -n "$FAL_KEY"       ]] && log "fal:      ${#FAL_KEY} chars"                 || warn "fal: missing"
[[ -n "$PIXABAY_KEY"   ]] && log "pixabay:  ${#PIXABAY_KEY} chars"             || warn "pixabay: pending approval"
[[ -n "$CF_API_TOKEN"  ]] && log "cf api token: ${#CF_API_TOKEN} chars"        || warn "cf api token: missing"
[[ -n "$CF_ACCOUNT"    ]] && log "cloudflare account_id: ${#CF_ACCOUNT} chars" || warn "cloudflare: pending R2 setup"
[[ -n "$R2_KEY_ID"     ]] && log "r2 access_key_id: ${#R2_KEY_ID} chars"       || warn "r2 access_key_id: not set (using API token auth)"
[[ -n "$R2_SECRET"     ]] && log "r2 secret: ${#R2_SECRET} chars"              || warn "r2 secret: not set (using API token auth)"
[[ -n "$R2_URL"        ]] && log "r2 public url: $R2_URL"                       || warn "r2 public url: pending"

# ── Write .env (atomic write via temp file) ───────────────────────────────────
TMPENV="$ENV_FILE.tmp.$$"
trap "rm -f '$TMPENV'" EXIT

cat > "$TMPENV" << ENVEOF
# ════════════════════════════════════════════════════════════
#  @pokerzeno/image-provider — active credentials
#  GENERATED by scripts/pull-secrets.sh — do not edit by hand
#  Source of truth: stolution:$VAULT_DIR/image-provider-*.env
#  Re-pull anytime: bash scripts/pull-secrets.sh
#  Last pulled: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# ════════════════════════════════════════════════════════════

# ─── Web Sources ─────────────────────────────────────────────────────────────
UNSPLASH_ACCESS_KEY=${UNSPLASH_KEY}
PEXELS_API_KEY=${PEXELS_KEY}
# TODO: add once Pixabay approves API key (usually 24-48h after signup)
PIXABAY_API_KEY=${PIXABAY_KEY}

# ─── AI Generation (fal.ai) ──────────────────────────────────────────────────
FAL_KEY=${FAL_KEY}

# ─── Cloudflare R2 Storage (Path B: CF API token auth) ───────────────────────
# CF API token is used directly for R2 object operations (no S3 creds needed)
CLOUDFLARE_ACCOUNT_ID=${CF_ACCOUNT}
CLOUDFLARE_API_TOKEN=${CF_API_TOKEN}
R2_ACCESS_KEY_ID=${R2_KEY_ID}
R2_SECRET_ACCESS_KEY=${R2_SECRET}
R2_BUCKET=${R2_BUCKET:-site-images}
R2_PUBLIC_BASE_URL=${R2_URL}

# ─── Storage Backend ─────────────────────────────────────────────────────────
STORAGE_BACKEND=r2

# ─── Budget Cap ──────────────────────────────────────────────────────────────
BUDGET_CAP_USD=1.00
ENVEOF

mv "$TMPENV" "$ENV_FILE"
chmod 600 "$ENV_FILE"
log ".env written ($(wc -l < "$ENV_FILE") lines, perms 600)"

# ── Cleanup ───────────────────────────────────────────────────────────────────
unset UNSPLASH_KEY PEXELS_KEY FAL_KEY PIXABAY_KEY CF_API_TOKEN CF_ACCOUNT R2_KEY_ID R2_SECRET R2_BUCKET R2_URL

log "done — run 'image-provider budget' to verify setup"
