import type { AuthorProfile, VoiceStyle, PostingCadence } from './types';

// Raw member data — mirrors POKER_MEMBERS from poker-zeno src/content/members.ts
// We embed just enough to build AuthorProfiles without importing from the site at runtime.
interface RawMember {
  id: string;
  username: string;
  firstName: string;
  lastName: string;
  city: string;
  region: string;
  tier: string;
  points: number;
  joinedDate: string;
  specialization: string;
}

const POKER_MEMBER_POOL: RawMember[] = [
  { id: 'm001', username: 'CardShark92', firstName: 'Marcus', lastName: 'Holloway', city: 'Las Vegas', region: 'North America', tier: 'Legend', points: 127450, joinedDate: 'Jan 2023', specialization: 'mixed' },
  { id: 'm002', username: 'RiverKing', firstName: 'Dante', lastName: 'Ferrara', city: 'New York', region: 'North America', tier: 'Legend', points: 134200, joinedDate: 'Mar 2022', specialization: 'tournament' },
  { id: 'm003', username: 'FlopDoctor', firstName: 'Ingrid', lastName: 'Bjornsen', city: 'Stockholm', region: 'Europe', tier: 'Legend', points: 131800, joinedDate: 'Feb 2022', specialization: 'gto' },
  { id: 'm004', username: 'TiltSlayer', firstName: 'Kwame', lastName: 'Asante', city: 'London', region: 'Europe', tier: 'Legend', points: 129600, joinedDate: 'Jun 2022', specialization: 'mixed' },
  { id: 'm005', username: 'AllInAnna', firstName: 'Anna', lastName: 'Kowalczyk', city: 'Warsaw', region: 'Europe', tier: 'Legend', points: 126300, joinedDate: 'Sep 2022', specialization: 'tournament' },
  { id: 'm006', username: 'PokerMaster21', firstName: 'Leon', lastName: 'Hartmann', city: 'Berlin', region: 'Europe', tier: 'Master', points: 98760, joinedDate: 'Apr 2022', specialization: 'gto' },
  { id: 'm007', username: 'HighStakesHero', firstName: 'Yuki', lastName: 'Tanaka', city: 'Tokyo', region: 'Asia', tier: 'Master', points: 87650, joinedDate: 'Jul 2022', specialization: 'cash' },
  { id: 'm008', username: 'CheckRaiser', firstName: 'Paulo', lastName: 'Mendes', city: 'Lisbon', region: 'Europe', tier: 'Master', points: 121400, joinedDate: 'Jan 2023', specialization: 'mixed' },
  { id: 'm009', username: 'PocketAces', firstName: 'Rhea', lastName: 'Iyer', city: 'Singapore', region: 'Asia', tier: 'Master', points: 117800, joinedDate: 'Feb 2023', specialization: 'tournament' },
  { id: 'm010', username: 'StreetBully', firstName: 'Connor', lastName: 'McBride', city: 'Chicago', region: 'North America', tier: 'Master', points: 113500, joinedDate: 'Mar 2023', specialization: 'cash' },
  { id: 'm011', username: 'MuckMaster', firstName: 'Fatima', lastName: 'Al-Rashid', city: 'Dubai', region: 'Asia', tier: 'Master', points: 109200, joinedDate: 'May 2023', specialization: 'mixed' },
  { id: 'm012', username: 'SolverSage', firstName: 'Erik', lastName: 'Lindqvist', city: 'Gothenburg', region: 'Europe', tier: 'Master', points: 105700, joinedDate: 'Apr 2023', specialization: 'gto' },
  { id: 'm013', username: 'NutPeddler', firstName: 'Adriana', lastName: 'Vasquez', city: 'Mexico City', region: 'North America', tier: 'Master', points: 102300, joinedDate: 'Jun 2023', specialization: 'cash' },
  { id: 'm014', username: 'OverbetOllie', firstName: 'Oliver', lastName: 'Grimes', city: 'Manchester', region: 'Europe', tier: 'Master', points: 99100, joinedDate: 'Jul 2023', specialization: 'tournament' },
  { id: 'm015', username: 'ICMGuru', firstName: 'Hyun', lastName: 'Park', city: 'Seoul', region: 'Asia', tier: 'Master', points: 95600, joinedDate: 'Aug 2023', specialization: 'tournament' },
  { id: 'm016', username: 'BarrelBlast', firstName: 'Nadia', lastName: 'Okafor', city: 'Lagos', region: 'Asia', tier: 'Master', points: 92400, joinedDate: 'Sep 2023', specialization: 'mixed' },
  { id: 'm017', username: 'ThreeBetTheo', firstName: 'Theodore', lastName: 'Crane', city: 'Boston', region: 'North America', tier: 'Master', points: 90800, joinedDate: 'Oct 2023', specialization: 'gto' },
  { id: 'm018', username: 'CalmMinds99', firstName: 'Priya', lastName: 'Nair', city: 'San Francisco', region: 'North America', tier: 'Expert', points: 76540, joinedDate: 'Nov 2022', specialization: 'mixed' },
  { id: 'm019', username: 'GrindMachine55', firstName: 'Franz', lastName: 'Weber', city: 'Vienna', region: 'Europe', tier: 'Expert', points: 65320, joinedDate: 'Dec 2022', specialization: 'cash' },
  { id: 'm020', username: 'FoldEquity', firstName: 'Serena', lastName: 'Johansson', city: 'Copenhagen', region: 'Europe', tier: 'Expert', points: 88300, joinedDate: 'Jan 2023', specialization: 'tournament' },
  { id: 'm021', username: 'BlockerBen', firstName: 'Benjamin', lastName: 'Choi', city: 'Vancouver', region: 'North America', tier: 'Expert', points: 85900, joinedDate: 'Feb 2023', specialization: 'gto' },
  { id: 'm022', username: 'RakeBeater', firstName: 'Simone', lastName: 'Fontana', city: 'Milan', region: 'Europe', tier: 'Expert', points: 83400, joinedDate: 'Mar 2023', specialization: 'cash' },
  { id: 'm023', username: 'SqueezePlay', firstName: 'DeShawn', lastName: 'Morris', city: 'Atlanta', region: 'North America', tier: 'Expert', points: 80700, joinedDate: 'Apr 2023', specialization: 'mixed' },
  { id: 'm024', username: 'DonkDani', firstName: 'Danielle', lastName: 'Kwan', city: 'Hong Kong', region: 'Asia', tier: 'Expert', points: 78200, joinedDate: 'May 2023', specialization: 'tournament' },
  { id: 'm025', username: 'GutterGus', firstName: 'Gustaf', lastName: 'Erickson', city: 'Oslo', region: 'Europe', tier: 'Expert', points: 75800, joinedDate: 'Jun 2023', specialization: 'mixed' },
  { id: 'm026', username: 'RangeAdvantage', firstName: 'Leila', lastName: 'Nazari', city: 'Toronto', region: 'North America', tier: 'Expert', points: 73100, joinedDate: 'Jul 2023', specialization: 'gto' },
  { id: 'm027', username: 'ColdCallCarla', firstName: 'Carla', lastName: 'Benedetti', city: 'Rome', region: 'Europe', tier: 'Expert', points: 70500, joinedDate: 'Aug 2023', specialization: 'cash' },
  { id: 'm028', username: 'HeadsUpHank', firstName: 'Henry', lastName: 'Ostrowski', city: 'Krakow', region: 'Europe', tier: 'Expert', points: 68200, joinedDate: 'Sep 2023', specialization: 'mixed' },
  { id: 'm029', username: 'WetBoardWendy', firstName: 'Wendy', lastName: 'Zhao', city: 'Shanghai', region: 'Asia', tier: 'Expert', points: 65900, joinedDate: 'Oct 2023', specialization: 'gto' },
  { id: 'm030', username: 'PokerNomad', firstName: 'Fabian', lastName: 'Reyes', city: 'Barcelona', region: 'Europe', tier: 'Expert', points: 63700, joinedDate: 'Nov 2023', specialization: 'cash' },
  { id: 'm031', username: 'EquityEdge', firstName: 'Soo-Jin', lastName: 'Lee', city: 'Seoul', region: 'Asia', tier: 'Advanced', points: 52100, joinedDate: 'Dec 2022', specialization: 'gto' },
  { id: 'm032', username: 'ValueTown', firstName: 'Marcus', lastName: 'Finley', city: 'Dublin', region: 'Europe', tier: 'Advanced', points: 49800, joinedDate: 'Jan 2023', specialization: 'cash' },
  { id: 'm033', username: 'RiverRat', firstName: 'Tatiana', lastName: 'Morozov', city: 'Moscow', region: 'Europe', tier: 'Advanced', points: 47500, joinedDate: 'Feb 2023', specialization: 'tournament' },
  { id: 'm034', username: 'TrapMaster', firstName: 'Jerome', lastName: 'Baptiste', city: 'Paris', region: 'Europe', tier: 'Advanced', points: 45300, joinedDate: 'Mar 2023', specialization: 'mixed' },
  { id: 'm035', username: 'BigBlindBob', firstName: 'Robert', lastName: 'Kovacs', city: 'Budapest', region: 'Europe', tier: 'Advanced', points: 43100, joinedDate: 'Apr 2023', specialization: 'cash' },
  { id: 'm036', username: 'SatelliteKing', firstName: 'Arnav', lastName: 'Sharma', city: 'Mumbai', region: 'Asia', tier: 'Advanced', points: 41200, joinedDate: 'May 2023', specialization: 'tournament' },
  { id: 'm037', username: 'SemiBluffSam', firstName: 'Samuel', lastName: 'Adewale', city: 'Accra', region: 'Asia', tier: 'Advanced', points: 39400, joinedDate: 'Jun 2023', specialization: 'mixed' },
  { id: 'm038', username: 'TightIsRight', firstName: 'Elina', lastName: 'Virtanen', city: 'Helsinki', region: 'Europe', tier: 'Advanced', points: 37800, joinedDate: 'Jul 2023', specialization: 'gto' },
  { id: 'm039', username: 'DeeplyStackedDave', firstName: 'David', lastName: 'Okoye', city: 'Nairobi', region: 'Asia', tier: 'Advanced', points: 36200, joinedDate: 'Aug 2023', specialization: 'cash' },
  { id: 'm040', username: 'PotGeometry', firstName: 'Hana', lastName: 'Novak', city: 'Prague', region: 'Europe', tier: 'Advanced', points: 34700, joinedDate: 'Sep 2023', specialization: 'gto' },
  { id: 'm041', username: 'UTGOpenner', firstName: 'Matteo', lastName: 'Russo', city: 'Naples', region: 'Europe', tier: 'Advanced', points: 33200, joinedDate: 'Oct 2023', specialization: 'tournament' },
  { id: 'm042', username: 'ChipLeaderChris', firstName: 'Christopher', lastName: 'Lane', city: 'Las Vegas', region: 'North America', tier: 'Advanced', points: 31800, joinedDate: 'Nov 2023', specialization: 'tournament' },
  { id: 'm043', username: 'FinalTableFred', firstName: 'Frederick', lastName: 'Olsen', city: 'Aarhus', region: 'Europe', tier: 'Advanced', points: 30500, joinedDate: 'Dec 2023', specialization: 'tournament' },
  { id: 'm044', username: 'StradleSteve', firstName: 'Steven', lastName: 'Park', city: 'Seattle', region: 'North America', tier: 'Advanced', points: 29200, joinedDate: 'Jan 2024', specialization: 'cash' },
  { id: 'm045', username: 'HomegameHarry', firstName: 'Harold', lastName: 'Nguyen', city: 'Houston', region: 'North America', tier: 'Advanced', points: 28100, joinedDate: 'Feb 2024', specialization: 'mixed' },
  { id: 'm046', username: 'MixedGameMike', firstName: 'Michael', lastName: 'Santos', city: 'Sao Paulo', region: 'North America', tier: 'Advanced', points: 26900, joinedDate: 'Mar 2024', specialization: 'mixed' },
  { id: 'm047', username: 'BoardTextureTom', firstName: 'Thomas', lastName: 'Kim', city: 'Busan', region: 'Asia', tier: 'Advanced', points: 25800, joinedDate: 'Apr 2024', specialization: 'gto' },
  { id: 'm048', username: 'BluffCatchBetty', firstName: 'Elisabeth', lastName: 'Muller', city: 'Zurich', region: 'Europe', tier: 'Advanced', points: 24700, joinedDate: 'May 2024', specialization: 'mixed' },
  { id: 'm049', username: 'ContinuationCarlos', firstName: 'Carlos', lastName: 'Rivera', city: 'Madrid', region: 'Europe', tier: 'Advanced', points: 23700, joinedDate: 'Jun 2024', specialization: 'cash' },
  { id: 'm050', username: 'ShortStackSuki', firstName: 'Suki', lastName: 'Yamamoto', city: 'Osaka', region: 'Asia', tier: 'Advanced', points: 22700, joinedDate: 'Jul 2024', specialization: 'tournament' },
  { id: 'm051', username: 'NitNate', firstName: 'Nathan', lastName: 'Cross', city: 'Edinburgh', region: 'Europe', tier: 'Skilled', points: 18200, joinedDate: 'Aug 2023', specialization: 'cash' },
  { id: 'm052', username: 'LAGLisa', firstName: 'Lisa', lastName: 'Perrone', city: 'Palermo', region: 'Europe', tier: 'Skilled', points: 17400, joinedDate: 'Sep 2023', specialization: 'mixed' },
  { id: 'm053', username: 'PushFoldPete', firstName: 'Peter', lastName: 'Andersen', city: 'Odense', region: 'Europe', tier: 'Skilled', points: 16800, joinedDate: 'Oct 2023', specialization: 'tournament' },
  { id: 'm054', username: 'AngleShooterAlex', firstName: 'Alexei', lastName: 'Volkov', city: 'St. Petersburg', region: 'Europe', tier: 'Skilled', points: 16200, joinedDate: 'Nov 2023', specialization: 'mixed' },
  { id: 'm055', username: 'MinBetMarco', firstName: 'Marco', lastName: 'Pellegrini', city: 'Florence', region: 'Europe', tier: 'Skilled', points: 15700, joinedDate: 'Dec 2023', specialization: 'cash' },
  { id: 'm056', username: 'SetMiningSteph', firstName: 'Stephanie', lastName: 'Laurent', city: 'Lyon', region: 'Europe', tier: 'Skilled', points: 15100, joinedDate: 'Jan 2024', specialization: 'cash' },
  { id: 'm057', username: 'LiveTellLuke', firstName: 'Lucas', lastName: 'Hoffmann', city: 'Frankfurt', region: 'Europe', tier: 'Skilled', points: 14600, joinedDate: 'Feb 2024', specialization: 'mixed' },
  { id: 'm058', username: 'DonkBetDiana', firstName: 'Diana', lastName: 'Popescu', city: 'Bucharest', region: 'Europe', tier: 'Skilled', points: 14100, joinedDate: 'Mar 2024', specialization: 'gto' },
  { id: 'm059', username: 'OmahaOscar', firstName: 'Oscar', lastName: 'Lindberg', city: 'Malmo', region: 'Europe', tier: 'Skilled', points: 13600, joinedDate: 'Apr 2024', specialization: 'mixed' },
  { id: 'm060', username: 'RakebackRod', firstName: 'Rodrigo', lastName: 'Alves', city: 'Porto', region: 'Europe', tier: 'Skilled', points: 13200, joinedDate: 'May 2024', specialization: 'cash' },
  { id: 'm061', username: 'SatSurfer', firstName: 'Sonia', lastName: 'Perez', city: 'Valencia', region: 'Europe', tier: 'Skilled', points: 12800, joinedDate: 'Jun 2024', specialization: 'tournament' },
  { id: 'm062', username: 'TurnBarrel', firstName: 'Bruno', lastName: 'Clement', city: 'Bordeaux', region: 'Europe', tier: 'Skilled', points: 12400, joinedDate: 'Jul 2024', specialization: 'mixed' },
  { id: 'm063', username: 'FlopTextureFelix', firstName: 'Felix', lastName: 'Gruber', city: 'Munich', region: 'Europe', tier: 'Skilled', points: 12000, joinedDate: 'Aug 2024', specialization: 'gto' },
  { id: 'm064', username: 'GapConceptGary', firstName: 'Gary', lastName: 'Mitchell', city: 'Glasgow', region: 'Europe', tier: 'Skilled', points: 11600, joinedDate: 'Sep 2024', specialization: 'tournament' },
  { id: 'm065', username: 'HandReadHannah', firstName: 'Hannah', lastName: 'Fischer', city: 'Hamburg', region: 'Europe', tier: 'Skilled', points: 11200, joinedDate: 'Oct 2024', specialization: 'mixed' },
  { id: 'm066', username: 'PosFishPaul', firstName: 'Paul', lastName: 'Mackenzie', city: 'Aberdeen', region: 'Europe', tier: 'Skilled', points: 10800, joinedDate: 'Nov 2024', specialization: 'cash' },
  { id: 'm067', username: 'NeutralNick', firstName: 'Nicolas', lastName: 'Patel', city: 'Leicester', region: 'Europe', tier: 'Skilled', points: 10500, joinedDate: 'Dec 2024', specialization: 'mixed' },
  { id: 'm068', username: 'UTGDefender', firstName: 'Uma', lastName: 'Krishnan', city: 'Chennai', region: 'Asia', tier: 'Skilled', points: 10100, joinedDate: 'Jan 2025', specialization: 'gto' },
  { id: 'm069', username: 'ButtonBoss', firstName: 'Boris', lastName: 'Petrov', city: 'Sofia', region: 'Europe', tier: 'Skilled', points: 9700, joinedDate: 'Feb 2025', specialization: 'cash' },
  { id: 'm070', username: 'PokerProdigy', firstName: 'Petra', lastName: 'Novakova', city: 'Brno', region: 'Europe', tier: 'Skilled', points: 9400, joinedDate: 'Mar 2025', specialization: 'tournament' },
  { id: 'm071', username: 'CasinoCarl', firstName: 'Carl', lastName: 'Johansson', city: 'Gothenburg', region: 'Europe', tier: 'Apprentice', points: 6200, joinedDate: 'Apr 2024', specialization: 'mixed' },
  { id: 'm072', username: 'NewbieNorman', firstName: 'Norman', lastName: 'Walsh', city: 'Bristol', region: 'Europe', tier: 'Apprentice', points: 5900, joinedDate: 'May 2024', specialization: 'cash' },
  { id: 'm073', username: 'LearnToFold', firstName: 'Lea', lastName: 'Schmidt', city: 'Stuttgart', region: 'Europe', tier: 'Apprentice', points: 5600, joinedDate: 'Jun 2024', specialization: 'mixed' },
  { id: 'm074', username: 'PokerPupil', firstName: 'Piotr', lastName: 'Kaminski', city: 'Gdansk', region: 'Europe', tier: 'Apprentice', points: 5300, joinedDate: 'Jul 2024', specialization: 'tournament' },
  { id: 'm075', username: 'CardCounter9', firstName: 'Carlos', lastName: 'Medina', city: 'Bogota', region: 'North America', tier: 'Apprentice', points: 5000, joinedDate: 'Aug 2024', specialization: 'gto' },
  { id: 'm076', username: 'RunItTwice', firstName: 'Rashid', lastName: 'Hassan', city: 'Casablanca', region: 'Asia', tier: 'Apprentice', points: 4800, joinedDate: 'Sep 2024', specialization: 'mixed' },
  { id: 'm077', username: 'VolatileVince', firstName: 'Vincent', lastName: 'Dupont', city: 'Toulouse', region: 'Europe', tier: 'Apprentice', points: 4600, joinedDate: 'Oct 2024', specialization: 'cash' },
  { id: 'm078', username: 'TightenUp', firstName: 'Tina', lastName: 'Braun', city: 'Cologne', region: 'Europe', tier: 'Apprentice', points: 4400, joinedDate: 'Nov 2024', specialization: 'gto' },
  { id: 'm079', username: 'CheckFoldCharlie', firstName: 'Charlie', lastName: 'Green', city: 'Leeds', region: 'Europe', tier: 'Apprentice', points: 4200, joinedDate: 'Dec 2024', specialization: 'cash' },
  { id: 'm080', username: 'PaperHandsPaula', firstName: 'Paula', lastName: 'Torres', city: 'Bilbao', region: 'Europe', tier: 'Apprentice', points: 4000, joinedDate: 'Jan 2025', specialization: 'tournament' },
  { id: 'm081', username: 'QuietObserver', firstName: 'Qian', lastName: 'Liu', city: 'Beijing', region: 'Asia', tier: 'Apprentice', points: 3800, joinedDate: 'Feb 2025', specialization: 'mixed' },
  { id: 'm082', username: 'FishingFrank', firstName: 'Frank', lastName: 'Mayer', city: 'Dresden', region: 'Europe', tier: 'Apprentice', points: 3600, joinedDate: 'Mar 2025', specialization: 'cash' },
  { id: 'm083', username: 'RiverChaser', firstName: 'Rita', lastName: 'Conti', city: 'Genoa', region: 'Europe', tier: 'Apprentice', points: 3400, joinedDate: 'Apr 2025', specialization: 'tournament' },
  { id: 'm084', username: 'SemiBluffSylvia', firstName: 'Sylvia', lastName: 'Baer', city: 'Bern', region: 'Europe', tier: 'Apprentice', points: 3200, joinedDate: 'May 2025', specialization: 'mixed' },
  { id: 'm085', username: 'MicrostakesMike', firstName: 'Mike', lastName: 'Petersen', city: 'Aarhus', region: 'Europe', tier: 'Apprentice', points: 3000, joinedDate: 'Jun 2025', specialization: 'cash' },
  { id: 'm086', username: 'FreerollFrank', firstName: 'Franz', lastName: 'Kaufmann', city: 'Biel', region: 'Europe', tier: 'Novice', points: 1200, joinedDate: 'Jul 2025', specialization: 'tournament' },
  { id: 'm087', username: 'JustLearning', firstName: 'Jennifer', lastName: 'Hall', city: 'Cardiff', region: 'Europe', tier: 'Novice', points: 1100, joinedDate: 'Aug 2025', specialization: 'mixed' },
  { id: 'm088', username: 'NoviceNate', firstName: 'Nathan', lastName: 'Bell', city: 'Coventry', region: 'Europe', tier: 'Novice', points: 950, joinedDate: 'Sep 2025', specialization: 'cash' },
  { id: 'm089', username: 'PokerFirst', firstName: 'Priscilla', lastName: 'Chan', city: 'Taipei', region: 'Asia', tier: 'Novice', points: 900, joinedDate: 'Oct 2025', specialization: 'tournament' },
  { id: 'm090', username: 'TableNewbie', firstName: 'Tobias', lastName: 'Wagner', city: 'Nuremberg', region: 'Europe', tier: 'Novice', points: 850, joinedDate: 'Nov 2025', specialization: 'mixed' },
  { id: 'm091', username: 'CardNovice', firstName: 'Camille', lastName: 'Blanc', city: 'Nice', region: 'Europe', tier: 'Novice', points: 800, joinedDate: 'Dec 2025', specialization: 'cash' },
  { id: 'm092', username: 'JustStarted', firstName: 'James', lastName: 'Osei', city: 'Kumasi', region: 'Asia', tier: 'Novice', points: 750, joinedDate: 'Jan 2026', specialization: 'gto' },
  { id: 'm093', username: 'LearningCurve', firstName: 'Linh', lastName: 'Nguyen', city: 'Hanoi', region: 'Asia', tier: 'Novice', points: 700, joinedDate: 'Feb 2026', specialization: 'mixed' },
  { id: 'm094', username: 'PokerRookie', firstName: 'Remy', lastName: 'Leclerc', city: 'Nantes', region: 'Europe', tier: 'Novice', points: 650, joinedDate: 'Mar 2026', specialization: 'tournament' },
  { id: 'm095', username: 'FirstHand', firstName: 'Fiona', lastName: 'Murray', city: 'Galway', region: 'Europe', tier: 'Novice', points: 600, joinedDate: 'Apr 2026', specialization: 'cash' },
  // Members 96-300 — generated deterministically for pool completeness
  { id: 'm096', username: 'StackedStan', firstName: 'Stanley', lastName: 'Berger', city: 'Denver', region: 'North America', tier: 'Skilled', points: 14300, joinedDate: 'Jun 2024', specialization: 'cash' },
  { id: 'm097', username: 'PokerPhilosopher', firstName: 'Philip', lastName: 'Bauer', city: 'Leipzig', region: 'Europe', tier: 'Skilled', points: 13900, joinedDate: 'Jul 2024', specialization: 'gto' },
  { id: 'm098', username: 'RunGoodRita', firstName: 'Rita', lastName: 'Flores', city: 'Monterrey', region: 'North America', tier: 'Skilled', points: 13500, joinedDate: 'Aug 2024', specialization: 'tournament' },
  { id: 'm099', username: 'CasinoVet', firstName: 'Victor', lastName: 'Ndiaye', city: 'Dakar', region: 'Asia', tier: 'Skilled', points: 13100, joinedDate: 'Sep 2024', specialization: 'mixed' },
  { id: 'm100', username: 'ProPatrick', firstName: 'Patrick', lastName: 'Flynn', city: 'Cork', region: 'Europe', tier: 'Skilled', points: 12700, joinedDate: 'Oct 2024', specialization: 'cash' },
  { id: 'm101', username: 'SolverStudent', firstName: 'Sofia', lastName: 'Ebert', city: 'Dortmund', region: 'Europe', tier: 'Skilled', points: 11900, joinedDate: 'Nov 2024', specialization: 'gto' },
  { id: 'm102', username: 'NightOwlNadia', firstName: 'Nadia', lastName: 'Ivanova', city: 'Kyiv', region: 'Europe', tier: 'Skilled', points: 11500, joinedDate: 'Dec 2024', specialization: 'mixed' },
  { id: 'm103', username: 'TourneyTiger', firstName: 'Taavi', lastName: 'Kask', city: 'Tallinn', region: 'Europe', tier: 'Skilled', points: 11100, joinedDate: 'Jan 2025', specialization: 'tournament' },
  { id: 'm104', username: 'CashGameCelia', firstName: 'Celia', lastName: 'Moreno', city: 'Seville', region: 'Europe', tier: 'Skilled', points: 10700, joinedDate: 'Feb 2025', specialization: 'cash' },
  { id: 'm105', username: 'EdgeSeeker', firstName: 'Elias', lastName: 'Guzman', city: 'Lima', region: 'North America', tier: 'Skilled', points: 10300, joinedDate: 'Mar 2025', specialization: 'gto' },
  { id: 'm106', username: 'ActionAlex', firstName: 'Alexander', lastName: 'Svensson', city: 'Uppsala', region: 'Europe', tier: 'Apprentice', points: 4700, joinedDate: 'Apr 2025', specialization: 'cash' },
  { id: 'm107', username: 'GrindingGreta', firstName: 'Greta', lastName: 'Holm', city: 'Linkoping', region: 'Europe', tier: 'Apprentice', points: 4500, joinedDate: 'May 2025', specialization: 'tournament' },
  { id: 'm108', username: 'PokerNewbie1', firstName: 'Nikolaj', lastName: 'Sorensen', city: 'Aalborg', region: 'Europe', tier: 'Apprentice', points: 4300, joinedDate: 'Jun 2025', specialization: 'mixed' },
  { id: 'm109', username: 'FeltFeeling', firstName: 'Fatou', lastName: 'Diallo', city: 'Abidjan', region: 'Asia', tier: 'Apprentice', points: 4100, joinedDate: 'Jul 2025', specialization: 'cash' },
  { id: 'm110', username: 'HeroCallHana', firstName: 'Hana', lastName: 'Suzuki', city: 'Nagoya', region: 'Asia', tier: 'Apprentice', points: 3900, joinedDate: 'Aug 2025', specialization: 'tournament' },
  { id: 'm111', username: 'FoldOrFight', firstName: 'Florian', lastName: 'Meyer', city: 'Bonn', region: 'Europe', tier: 'Apprentice', points: 3700, joinedDate: 'Sep 2025', specialization: 'gto' },
  { id: 'm112', username: 'CardSharkJr', firstName: 'Chidi', lastName: 'Eze', city: 'Enugu', region: 'Asia', tier: 'Apprentice', points: 3500, joinedDate: 'Oct 2025', specialization: 'mixed' },
  { id: 'm113', username: 'PokerStarter', firstName: 'Penelope', lastName: 'White', city: 'Brighton', region: 'Europe', tier: 'Novice', points: 1050, joinedDate: 'Nov 2025', specialization: 'cash' },
  { id: 'm114', username: 'TableFreshman', firstName: 'Tomas', lastName: 'Blaho', city: 'Bratislava', region: 'Europe', tier: 'Novice', points: 980, joinedDate: 'Dec 2025', specialization: 'tournament' },
  { id: 'm115', username: 'WinOrLearn', firstName: 'Wanjiku', lastName: 'Kamau', city: 'Nairobi', region: 'Asia', tier: 'Novice', points: 870, joinedDate: 'Jan 2026', specialization: 'mixed' },
  { id: 'm116', username: 'CardCurious', firstName: 'Catalina', lastName: 'Ionescu', city: 'Cluj', region: 'Europe', tier: 'Novice', points: 820, joinedDate: 'Feb 2026', specialization: 'cash' },
  { id: 'm117', username: 'TableTourist', firstName: 'Timur', lastName: 'Kazakov', city: 'Almaty', region: 'Asia', tier: 'Novice', points: 780, joinedDate: 'Mar 2026', specialization: 'gto' },
  { id: 'm118', username: 'NewCardPlayer', firstName: 'Nuala', lastName: 'O\'Brien', city: 'Limerick', region: 'Europe', tier: 'Novice', points: 730, joinedDate: 'Apr 2026', specialization: 'mixed' },
  // Padding to 300 with varied profiles
  { id: 'm119', username: 'DeepRunDena', firstName: 'Dena', lastName: 'Walters', city: 'Phoenix', region: 'North America', tier: 'Advanced', points: 27600, joinedDate: 'May 2024', specialization: 'tournament' },
  { id: 'm120', username: 'MultiTableMax', firstName: 'Maxwell', lastName: 'Jordan', city: 'Minneapolis', region: 'North America', tier: 'Advanced', points: 26400, joinedDate: 'Jun 2024', specialization: 'mixed' },
  { id: 'm121', username: 'SixMaxSimon', firstName: 'Simon', lastName: 'Brooks', city: 'Portland', region: 'North America', tier: 'Advanced', points: 25300, joinedDate: 'Jul 2024', specialization: 'cash' },
  { id: 'm122', username: 'LiveRegLorrie', firstName: 'Lorrie', lastName: 'Castro', city: 'Miami', region: 'North America', tier: 'Advanced', points: 24200, joinedDate: 'Aug 2024', specialization: 'cash' },
  { id: 'm123', username: 'OnlineGrinder', firstName: 'Owen', lastName: 'Campbell', city: 'Montreal', region: 'North America', tier: 'Advanced', points: 23100, joinedDate: 'Sep 2024', specialization: 'gto' },
  { id: 'm124', username: 'StudLoSteph', firstName: 'Stephanie', lastName: 'King', city: 'Detroit', region: 'North America', tier: 'Advanced', points: 22100, joinedDate: 'Oct 2024', specialization: 'mixed' },
  { id: 'm125', username: 'TexasTough', firstName: 'Tyler', lastName: 'Ross', city: 'Dallas', region: 'North America', tier: 'Skilled', points: 16500, joinedDate: 'Nov 2024', specialization: 'cash' },
  { id: 'm126', username: 'VegasVince', firstName: 'Vincent', lastName: 'Stone', city: 'Las Vegas', region: 'North America', tier: 'Skilled', points: 15800, joinedDate: 'Dec 2024', specialization: 'tournament' },
  { id: 'm127', username: 'ActionJackson', firstName: 'Jackson', lastName: 'Porter', city: 'New Orleans', region: 'North America', tier: 'Skilled', points: 15200, joinedDate: 'Jan 2025', specialization: 'mixed' },
  { id: 'm128', username: 'CaliforniaCasino', firstName: 'Caden', lastName: 'Hughes', city: 'Los Angeles', region: 'North America', tier: 'Skilled', points: 14700, joinedDate: 'Feb 2025', specialization: 'cash' },
  { id: 'm129', username: 'NordicNils', firstName: 'Nils', lastName: 'Eriksson', city: 'Linkoping', region: 'Europe', tier: 'Skilled', points: 14200, joinedDate: 'Mar 2025', specialization: 'gto' },
  { id: 'm130', username: 'PokerPatricia', firstName: 'Patricia', lastName: 'Weiss', city: 'Hannover', region: 'Europe', tier: 'Skilled', points: 13700, joinedDate: 'Apr 2025', specialization: 'tournament' },
  { id: 'm131', username: 'ReadingRanges', firstName: 'Ramon', lastName: 'Diaz', city: 'Zaragoza', region: 'Europe', tier: 'Skilled', points: 13300, joinedDate: 'May 2025', specialization: 'mixed' },
  { id: 'm132', username: 'PositionPower', firstName: 'Paola', lastName: 'Ferrari', city: 'Turin', region: 'Europe', tier: 'Skilled', points: 12900, joinedDate: 'Jun 2025', specialization: 'cash' },
  { id: 'm133', username: 'AceAggressor', firstName: 'Antoine', lastName: 'Martin', city: 'Marseille', region: 'Europe', tier: 'Skilled', points: 12500, joinedDate: 'Jul 2025', specialization: 'gto' },
  { id: 'm134', username: 'SpadesSpecialist', firstName: 'Sandra', lastName: 'Horta', city: 'Lisbon', region: 'Europe', tier: 'Skilled', points: 12100, joinedDate: 'Aug 2025', specialization: 'mixed' },
  { id: 'm135', username: 'HeartsHunter', firstName: 'Henrik', lastName: 'Larsen', city: 'Frederiksberg', region: 'Europe', tier: 'Skilled', points: 11700, joinedDate: 'Sep 2025', specialization: 'tournament' },
  { id: 'm136', username: 'DiamondsDave', firstName: 'Damiano', lastName: 'Rossi', city: 'Bologna', region: 'Europe', tier: 'Skilled', points: 11300, joinedDate: 'Oct 2025', specialization: 'cash' },
  { id: 'm137', username: 'ClubsChampion', firstName: 'Christoph', lastName: 'Becker', city: 'Wiesbaden', region: 'Europe', tier: 'Skilled', points: 10900, joinedDate: 'Nov 2025', specialization: 'mixed' },
  { id: 'm138', username: 'AsianEdge', firstName: 'Aiko', lastName: 'Fujita', city: 'Kobe', region: 'Asia', tier: 'Skilled', points: 10500, joinedDate: 'Dec 2025', specialization: 'gto' },
  { id: 'm139', username: 'ShangPoker', firstName: 'Shanshan', lastName: 'Wang', city: 'Shenzhen', region: 'Asia', tier: 'Skilled', points: 10100, joinedDate: 'Jan 2026', specialization: 'mixed' },
  { id: 'm140', username: 'IndiaIndomitable', firstName: 'Ishaan', lastName: 'Verma', city: 'Bangalore', region: 'Asia', tier: 'Skilled', points: 9800, joinedDate: 'Feb 2026', specialization: 'tournament' },
  // Round out to 300 — using compact entries
  ...Array.from({ length: 160 }, (_, i) => ({
    id: `m${141 + i}`,
    username: `Player${141 + i}`,
    firstName: ['Aiden','Bianca','Cedric','Diana','Emeka','Freya','Gunnar','Helena','Igor','Juno'][i % 10],
    lastName: ['Adams','Brown','Clark','Davis','Evans','Ford','Grant','Hayes','Ito','Jones'][i % 10],
    city: ['London','Paris','Berlin','Tokyo','Sydney','Lagos','Cairo','Mumbai','Seoul','Toronto'][i % 10],
    region: ['Europe','Europe','Europe','Asia','Asia','Asia','Asia','Asia','Asia','North America'][i % 10],
    tier: i < 20 ? 'Advanced' : i < 60 ? 'Skilled' : i < 100 ? 'Apprentice' : 'Novice',
    points: Math.max(400, 8000 - i * 45),
    joinedDate: `Jan 2026`,
    specialization: (['cash','tournament','mixed','gto'] as const)[i % 4],
  })),
];

const VOICE_MAP: VoiceStyle[] = ['casual', 'analytical', 'pro-jargon', 'storytelling', 'dry-humor'];
const EXPERTISE_MAP: Record<string, string[]> = {
  cash: ['cash games', 'live reads', 'position play', 'table selection'],
  tournament: ['ICM', 'stack management', 'bubble play', 'satellite strategy'],
  mixed: ['range construction', 'game selection', 'variance management'],
  gto: ['solver work', 'GTO baselines', 'frequency-based play', 'blockers'],
};

function assignCadence(idx: number): PostingCadence {
  if (idx < 30) return 'daily';
  if (idx < 150) return 'weekly';
  if (idx < 300) return 'monthly';
  return 'lurker';
}

export const POKER_AUTHOR_PROFILES: AuthorProfile[] = POKER_MEMBER_POOL.slice(0, 300).map((m, idx) => ({
  id: m.id,
  username: m.username,
  firstName: m.firstName,
  lastName: m.lastName,
  city: m.city,
  region: m.region,
  voice: VOICE_MAP[idx % VOICE_MAP.length],
  cadence: assignCadence(idx),
  expertiseTags: EXPERTISE_MAP[m.specialization] ?? ['poker fundamentals'],
  memberSince: m.joinedDate,
  tier: m.tier,
  role: 'member',
}));

export const POKER_SME_PROFILES: AuthorProfile[] = [
  {
    id: 'sme-p001', username: 'dr-elena-martinez', firstName: 'Elena', lastName: 'Martinez',
    city: 'Cambridge', region: 'North America', voice: 'analytical', cadence: 'weekly',
    expertiseTags: ['tournament statistics', 'variance analysis', 'win-rate modeling'],
    memberSince: 'Jan 2024', tier: 'sme', role: 'sme',
    bio: 'Dr. Martinez holds a PhD in applied statistics from MIT and has published extensively on tournament poker EV modeling. She consults for major tournament operators on prize structure design.',
    credentials: 'PhD Applied Statistics, MIT; 12 peer-reviewed publications',
    publicationCount: 12,
    linkedinOneliner: 'Tournament statistician | Poker EV researcher | MIT PhD',
  },
  {
    id: 'sme-p002', username: 'prof-james-chen', firstName: 'James', lastName: 'Chen',
    city: 'Stanford', region: 'North America', voice: 'analytical', cadence: 'weekly',
    expertiseTags: ['game theory', 'Nash equilibria', 'GTO play'],
    memberSince: 'Feb 2024', tier: 'sme', role: 'sme',
    bio: 'Prof. Chen is a Stanford game theorist whose research on incomplete-information games has been cited by professional poker solvers. He teaches computational game theory.',
    credentials: 'Professor, Stanford Computer Science; GTO theory researcher',
    publicationCount: 18,
    linkedinOneliner: 'Game theorist | Poker solver researcher | Stanford',
  },
  {
    id: 'sme-p003', username: 'dr-lisa-wong', firstName: 'Lisa', lastName: 'Wong',
    city: 'Hong Kong', region: 'Asia', voice: 'pro-jargon', cadence: 'weekly',
    expertiseTags: ['range construction', 'equity realization', 'multiway dynamics'],
    memberSince: 'Mar 2024', tier: 'sme', role: 'sme',
    bio: 'Dr. Wong spent eight years as a professional high-stakes cash game player before pursuing a doctorate in behavioural economics. She bridges academic theory and practical application.',
    credentials: 'PhD Behavioural Economics, HKU; Former high-stakes professional',
    publicationCount: 9,
    linkedinOneliner: 'Poker professional turned researcher | Equity theory',
  },
  {
    id: 'sme-p004', username: 'prof-david-kumar', firstName: 'David', lastName: 'Kumar',
    city: 'Bangalore', region: 'Asia', voice: 'analytical', cadence: 'weekly',
    expertiseTags: ['probability theory', 'bankroll science', 'Kelly criterion'],
    memberSince: 'Apr 2024', tier: 'sme', role: 'sme',
    bio: 'Prof. Kumar researches decision-making under uncertainty at IISc Bangalore. His work on optimal bankroll sizing under realistic variance models is widely cited in poker literature.',
    credentials: 'Associate Professor, IISc; Decision theory specialist',
    publicationCount: 14,
    linkedinOneliner: 'Decision theory | Bankroll optimization | IISc',
  },
  {
    id: 'sme-p005', username: 'dr-sarah-obrien', firstName: 'Sarah', lastName: "O'Brien",
    city: 'Dublin', region: 'Europe', voice: 'storytelling', cadence: 'weekly',
    expertiseTags: ['tilt psychology', 'mental game', 'performance coaching'],
    memberSince: 'May 2024', tier: 'sme', role: 'sme',
    bio: 'Dr. O\'Brien is a sports psychologist who works with top-ranked poker professionals on performance optimization and tilt management. Her "Steady State" framework is used by WPT regulars.',
    credentials: 'PhD Sports Psychology, UCD; Certified performance coach',
    publicationCount: 7,
    linkedinOneliner: 'Poker mental game coach | Sports psychologist | Dublin',
  },
  {
    id: 'sme-p006', username: 'prof-marcus-webb', firstName: 'Marcus', lastName: 'Webb',
    city: 'London', region: 'Europe', voice: 'analytical', cadence: 'weekly',
    expertiseTags: ['live poker tells', 'behavioral cues', 'table dynamics'],
    memberSince: 'Jun 2024', tier: 'sme', role: 'sme',
    bio: 'Prof. Webb is a behavioural scientist at UCL who has spent a decade studying non-verbal communication in high-stakes poker environments. He advises on live tell identification.',
    credentials: 'Professor of Behavioural Science, UCL; Live poker consultant',
    publicationCount: 11,
    linkedinOneliner: 'Behavioural science | Poker tells research | UCL',
  },
  {
    id: 'sme-p007', username: 'dr-yuki-hasegawa', firstName: 'Yuki', lastName: 'Hasegawa',
    city: 'Tokyo', region: 'Asia', voice: 'analytical', cadence: 'weekly',
    expertiseTags: ['heads-up play', 'exploitative adjustments', 'online poker metrics'],
    memberSince: 'Jul 2024', tier: 'sme', role: 'sme',
    bio: 'Dr. Hasegawa is a data scientist who developed statistical tools used by several major online poker rooms. His exploitability scoring framework has influenced poker training software.',
    credentials: 'PhD Data Science, Tokyo University; Poker analytics consultant',
    publicationCount: 6,
    linkedinOneliner: 'Poker data science | Exploitability modeling | Tokyo',
  },
  {
    id: 'sme-p008', username: 'prof-amara-osei', firstName: 'Amara', lastName: 'Osei',
    city: 'Accra', region: 'Asia', voice: 'pro-jargon', cadence: 'weekly',
    expertiseTags: ['mixed games', 'stud variants', 'HORSE strategy'],
    memberSince: 'Aug 2024', tier: 'sme', role: 'sme',
    bio: 'Prof. Osei is West Africa\'s most decorated poker tournament player, a three-time African Poker Championship finalist and researcher in mixed-game equilibria at the University of Ghana.',
    credentials: 'Lecturer, University of Ghana; 3x African Poker Championship finalist',
    publicationCount: 5,
    linkedinOneliner: 'Mixed game theorist | Champion | University of Ghana',
  },
  {
    id: 'sme-p009', username: 'dr-nikolaj-petrov', firstName: 'Nikolaj', lastName: 'Petrov',
    city: 'Copenhagen', region: 'Europe', voice: 'analytical', cadence: 'weekly',
    expertiseTags: ['ICM theory', 'final table strategy', 'deal-making mathematics'],
    memberSince: 'Sep 2024', tier: 'sme', role: 'sme',
    bio: 'Dr. Petrov authored the landmark study on ICM deal-making accuracy that reformed how major tournaments handle final-table chops. He consults on tournament structure.',
    credentials: 'PhD Mathematics, DTU Copenhagen; ICM theory researcher',
    publicationCount: 8,
    linkedinOneliner: 'ICM mathematician | Tournament consultant | DTU',
  },
  {
    id: 'sme-p010', username: 'prof-leila-ahmadi', firstName: 'Leila', lastName: 'Ahmadi',
    city: 'Toronto', region: 'North America', voice: 'analytical', cadence: 'weekly',
    expertiseTags: ['solver methodology', 'abstraction techniques', 'CFR algorithms'],
    memberSince: 'Oct 2024', tier: 'sme', role: 'sme',
    bio: 'Prof. Ahmadi is a machine learning researcher at the University of Toronto whose work on counterfactual regret minimization algorithms directly informs modern poker solver design.',
    credentials: 'Associate Professor, University of Toronto; ML & CFR researcher',
    publicationCount: 16,
    linkedinOneliner: 'CFR algorithms | Poker AI | UofT',
  },
];

export const ALL_POKER_AUTHORS: AuthorProfile[] = [
  ...POKER_AUTHOR_PROFILES,
  ...POKER_SME_PROFILES,
];
