/**
 * Render a Curator daily-digest markdown from a ScanRunResult.
 *
 * Output layout (per `curator_agent_directive.md` ## Output modes):
 *
 *   # Curator Digest — YYYY-MM-DD
 *
 *   ## Top findings
 *     <ranked list, top-N>
 *
 *   ## All findings by category
 *     <grouped subsections>
 *
 *   ## Scanner run summary
 *     <table: scanner | duration | finding count | error>
 *
 *   ## Provenance
 *     <run-window timing, repo SHA snapshot, env summary>
 */

import { rankFindings } from './orchestrator.js';
import type { Category, Finding, ScanRunResult } from './types.js';

const SEVERITY_ORDER: Record<string, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
  info: 4
};

/** Severity → markdown badge / emoji-free marker. */
function sevLabel(sev: string): string {
  switch (sev) {
    case 'critical':
      return '[CRITICAL]';
    case 'high':
      return '[HIGH]';
    case 'medium':
      return '[MED]';
    case 'low':
      return '[LOW]';
    default:
      return '[INFO]';
  }
}

/**
 * Render the digest. Returns the full markdown string ready to write to
 * `~/Documents/projects/reports/curator/YYYY-MM-DD-digest.md`.
 *
 * `topN` defaults to 10 — the directive's "top-N actionable findings".
 */
export function renderDigest(
  result: ScanRunResult,
  opts: { topN?: number; date?: Date } = {}
): string {
  const topN = opts.topN ?? 10;
  const date = opts.date ?? new Date();
  const dateStr = `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}-${String(date.getUTCDate()).padStart(2, '0')}`;

  const ranked = rankFindings(result.findings);
  const top = ranked.slice(0, topN);

  const lines: string[] = [];
  lines.push(`# Curator Digest — ${dateStr}`);
  lines.push('');
  lines.push(`Run: ${result.startedAt} → ${result.endedAt}`);
  lines.push(
    `Findings: ${result.findings.length} total (${countBy(result.findings, 'severity')})`
  );
  lines.push('');

  // Top findings
  lines.push(`## Top ${Math.min(topN, top.length)} findings`);
  lines.push('');
  if (top.length === 0) {
    lines.push('_No findings — system is in good shape, or no scanners ran._');
    lines.push('');
  } else {
    for (let i = 0; i < top.length; i++) {
      const f = top[i]!;
      lines.push(
        `### ${i + 1}. ${sevLabel(f.severity)} ${f.title}  _(${f.dimension})_`
      );
      lines.push('');
      lines.push(`- **Category**: ${f.category}`);
      lines.push(`- **Scanner**: \`${f.scannerId}\``);
      lines.push(`- **Effort**: ${f.effort}  •  **Impact**: ${f.impactScore}/100`);
      lines.push('');
      lines.push(f.detail);
      if (f.evidence.length > 0) {
        lines.push('');
        lines.push('**Evidence**:');
        for (const e of f.evidence) lines.push(`- ${e}`);
      }
      lines.push('');
      lines.push(`**Recommendation**: ${f.recommendation}`);
      lines.push('');
    }
  }

  // All findings by category
  lines.push('## All findings by category');
  lines.push('');
  if (result.findings.length === 0) {
    lines.push('_No findings._');
    lines.push('');
  } else {
    const grouped = groupByCategory(result.findings);
    for (const cat of Object.keys(grouped).sort() as Category[]) {
      lines.push(`### ${cat}`);
      lines.push('');
      const sorted = [...grouped[cat]!].sort(
        (a, b) =>
          (SEVERITY_ORDER[a.severity] ?? 9) - (SEVERITY_ORDER[b.severity] ?? 9)
      );
      for (const f of sorted) {
        lines.push(
          `- ${sevLabel(f.severity)} **${f.title}** _(${f.dimension}, scanner: \`${f.scannerId}\`)_ — ${f.recommendation}`
        );
      }
      lines.push('');
    }
  }

  // Scanner run summary
  lines.push('## Scanner run summary');
  lines.push('');
  lines.push('| Scanner | Duration (ms) | Findings | Error |');
  lines.push('|---|---:|---:|---|');
  for (const ps of result.perScanner) {
    const err = ps.error ? `\`${ps.error.replace(/\|/g, '\\|')}\`` : '';
    lines.push(
      `| \`${ps.scannerId}\` (${ps.name}) | ${ps.durationMs} | ${ps.findingCount} | ${err} |`
    );
  }
  lines.push('');

  // Provenance
  lines.push('## Provenance');
  lines.push('');
  lines.push(
    `- Generated by \`@chiefaia/curator\` Phase-1 daily digest at ${date.toISOString()}.`
  );
  lines.push(
    '- Scope: Phase-1 representative scanner set (memory drift, stale TODOs, open-PR age, worktree count, dependabot CVEs).'
  );
  lines.push(
    '- The full 80-dimension taxonomy is rolled out incrementally in subsequent PRs per `agent/memory/curator_agent_directive.md`.'
  );
  lines.push('');

  return lines.join('\n');
}

function countBy(items: Finding[], key: 'severity'): string {
  const counts: Record<string, number> = {};
  for (const f of items) {
    const k = f[key];
    counts[k] = (counts[k] ?? 0) + 1;
  }
  const order = ['critical', 'high', 'medium', 'low', 'info'];
  const parts: string[] = [];
  for (const k of order) {
    if (counts[k]) parts.push(`${counts[k]} ${k}`);
  }
  return parts.length === 0 ? '0' : parts.join(', ');
}

function groupByCategory(findings: Finding[]): Record<Category, Finding[]> {
  const out: Partial<Record<Category, Finding[]>> = {};
  for (const f of findings) {
    if (!out[f.category]) out[f.category] = [];
    out[f.category]!.push(f);
  }
  return out as Record<Category, Finding[]>;
}
