// A.9.8 — Live displacement dashboard.
//
// Single-page HTML served from `GET /dashboard`. Polls `GET /metrics`
// every 5 seconds and renders four panels:
//
//   1. Headline displacement % (local share vs claude share)
//   2. Escalation rate (cache misses + claude calls / total)
//   3. Per-model usage (rows from llm_router_task_calls_total)
//   4. Top-3 routing task-types by volume
//
// Plus the Claude per-hour budget guard (A.9.5) and total saved USD.
//
// Self-contained: no external CDN, no build step, no auth — Tailscale ACL
// is the perimeter. The HTML is generated by a single template function
// (no template engine) and served as `text/html`. Charts are inline SVG
// bars rendered by hand-rolled DOM updates — keeps the page < 6 KB on
// the wire and removes the operator-side npm install burden.
//
// Data source: `/metrics` Prometheus exposition. We re-parse it
// client-side rather than expose a new `/metrics.json` route — single
// surface to maintain, and any future Grafana scrape sees the same
// data.

const DASHBOARD_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>local-llm-router — displacement dashboard</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  * { box-sizing: border-box; }
  body { font: 14px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         margin: 0; padding: 16px; background: #0e0f12; color: #e4e6eb; }
  h1 { font-size: 18px; margin: 0 0 16px; color: #b1c5ff; font-weight: 600; }
  h2 { font-size: 13px; margin: 0 0 8px; color: #8a95a8; font-weight: 500;
       text-transform: uppercase; letter-spacing: 0.6px; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit,minmax(280px,1fr));
          gap: 12px; margin-bottom: 16px; }
  .card { background: #1a1d24; border-radius: 8px; padding: 14px; }
  .big { font: 32px/1.0 -apple-system; font-weight: 600; margin: 4px 0 6px; }
  .big.good { color: #66dba0; }
  .big.warn { color: #ffd166; }
  .big.bad  { color: #ff6b6b; }
  .sub { font-size: 12px; color: #8a95a8; }
  .row { display: flex; justify-content: space-between; align-items: center;
         padding: 4px 0; border-bottom: 1px solid #232830; }
  .row:last-child { border-bottom: none; }
  .row .k { color: #d4d8e0; flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .row .v { color: #66dba0; font-variant-numeric: tabular-nums; margin-left: 10px; }
  .row .v.claude { color: #ffd166; }
  .row .v.cache { color: #b1c5ff; }
  .bar { display: flex; height: 8px; border-radius: 4px; overflow: hidden;
         background: #232830; margin: 6px 0; }
  .bar > div { height: 100%; }
  .bar .local  { background: #66dba0; }
  .bar .claude { background: #ffd166; }
  .bar .cache  { background: #b1c5ff; }
  .footer { color: #5c6577; font-size: 11px; margin-top: 16px; }
  .err { color: #ff6b6b; font-size: 12px; padding: 6px 10px;
         background: #2c1518; border-radius: 4px; margin-bottom: 10px; display: none; }
  .err.on { display: block; }
  code { font-family: ui-monospace, Menlo, monospace; background: #232830;
         padding: 1px 4px; border-radius: 3px; font-size: 12px; }
</style>
</head>
<body>
<h1>local-llm-router — live displacement dashboard</h1>
<div class="err" id="err"></div>
<div class="grid">
  <div class="card">
    <h2>Displacement (local share)</h2>
    <div class="big" id="displacement">—</div>
    <div class="bar" id="displacement-bar">
      <div class="local" style="width:0"></div>
      <div class="claude" style="width:0"></div>
      <div class="cache" style="width:0"></div>
    </div>
    <div class="sub">
      <span class="v" id="d-local">0</span> local /
      <span class="v claude" id="d-claude">0</span> claude /
      <span class="v cache" id="d-cache">0</span> cache
    </div>
  </div>
  <div class="card">
    <h2>Escalation rate (→ claude)</h2>
    <div class="big" id="escalation">—</div>
    <div class="sub">Claude calls as a share of total. Lower is better.</div>
  </div>
  <div class="card">
    <h2>Estimated saved (vs all-Claude)</h2>
    <div class="big good" id="saved">$0.00</div>
    <div class="sub">Baseline − actual, since router restart.</div>
  </div>
  <div class="card">
    <h2>Claude budget (rolling 1h)</h2>
    <div class="big" id="budget">— / —</div>
    <div class="sub" id="budget-sub">cap = 60 calls/hour by default.</div>
  </div>
</div>

<div class="grid">
  <div class="card">
    <h2>Top-3 routing classes by volume</h2>
    <div id="top3">no data yet</div>
  </div>
  <div class="card">
    <h2>Per-task usage (all rows)</h2>
    <div id="pertask" style="max-height: 280px; overflow-y: auto;">no data yet</div>
  </div>
  <div class="card">
    <h2>Avg dispatch duration</h2>
    <div class="big" id="dur">— ms</div>
    <div class="sub">Mean across all dispatches.</div>
  </div>
</div>
<div class="footer">
  Polls <code>/metrics</code> every 5 s. Source: <code>llmMetrics.snapshot()</code> · A.9.8.
  Counter resets on daemon restart.
</div>
<script>
(function () {
  var POLL_MS = 5000;
  var err = document.getElementById('err');

  function parseMetrics(text) {
    var snap = {
      local: 0, claude: 0, cache: 0,
      localShare: 0, savedUsd: 0, avgDurationMs: 0,
      budgetCap: 0, budgetUsed: 0,
      perTask: {} // taskType -> { local, claude, cache }
    };
    var lines = text.split('\\n');
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      if (line === '' || line.charAt(0) === '#') continue;
      var m = line.match(/^(\\w+)(\\{[^}]*\\})?\\s+(\\S+)$/);
      if (m === null) continue;
      var metric = m[1];
      var labels = m[2] || '';
      var raw = m[3];
      var val = parseFloat(raw);
      if (!isFinite(val)) continue;
      if (metric === 'llm_router_calls_total') {
        if (labels.indexOf('provider="local"') >= 0) snap.local = val;
        else if (labels.indexOf('provider="claude"') >= 0) snap.claude = val;
        else if (labels.indexOf('provider="cache"') >= 0) snap.cache = val;
      } else if (metric === 'llm_router_local_share') snap.localShare = val;
      else if (metric === 'llm_router_saved_usd') snap.savedUsd = val;
      else if (metric === 'llm_router_avg_duration_ms') snap.avgDurationMs = val;
      else if (metric === 'llm_router_claude_budget_cap') snap.budgetCap = val;
      else if (metric === 'llm_router_claude_budget_calls_last_hour') snap.budgetUsed = val;
      else if (metric === 'llm_router_task_calls_total') {
        var tm = labels.match(/task_type="([^"]*)".*provider="([^"]*)"/);
        if (tm !== null) {
          var t = tm[1], p = tm[2];
          var row = snap.perTask[t];
          if (row === undefined) { row = { local: 0, claude: 0, cache: 0 }; snap.perTask[t] = row; }
          if (p === 'local') row.local = val;
          else if (p === 'claude') row.claude = val;
          else if (p === 'cache') row.cache = val;
        }
      }
    }
    return snap;
  }

  function classify(share) {
    if (share >= 0.90) return 'good';
    if (share >= 0.643) return 'good';
    if (share >= 0.40) return 'warn';
    return 'bad';
  }

  function render(snap) {
    err.classList.remove('on');
    var total = snap.local + snap.claude + snap.cache;
    var sharePct = total === 0 ? 0 : Math.round(snap.localShare * 1000) / 10;
    var displacement = document.getElementById('displacement');
    displacement.textContent = total === 0 ? '— %' : sharePct.toFixed(1) + ' %';
    displacement.className = 'big ' + classify(snap.localShare);

    var bar = document.getElementById('displacement-bar');
    var children = bar.children;
    if (total > 0) {
      children[0].style.width = (snap.local / total * 100) + '%';
      children[1].style.width = (snap.claude / total * 100) + '%';
      children[2].style.width = (snap.cache / total * 100) + '%';
    }
    document.getElementById('d-local').textContent = snap.local;
    document.getElementById('d-claude').textContent = snap.claude;
    document.getElementById('d-cache').textContent = snap.cache;

    var nonCache = snap.local + snap.claude;
    var escalation = nonCache === 0 ? 0 : snap.claude / nonCache;
    var eEl = document.getElementById('escalation');
    eEl.textContent = nonCache === 0 ? '— %' : (Math.round(escalation * 1000) / 10).toFixed(1) + ' %';
    eEl.className = 'big ' + (escalation <= 0.10 ? 'good' : escalation <= 0.357 ? 'warn' : 'bad');

    document.getElementById('saved').textContent = '$' + snap.savedUsd.toFixed(2);

    var budget = document.getElementById('budget');
    budget.textContent = snap.budgetUsed + ' / ' + (snap.budgetCap === 0 ? '∞' : snap.budgetCap);
    budget.className = 'big ' + (snap.budgetCap === 0 || snap.budgetUsed / snap.budgetCap < 0.7
                                  ? 'good'
                                  : snap.budgetUsed / snap.budgetCap < 0.9 ? 'warn' : 'bad');
    document.getElementById('budget-sub').textContent = snap.budgetCap === 0
      ? 'budget disabled (CLAUDE_CALLS_PER_HOUR_CAP=0)'
      : 'cap = ' + snap.budgetCap + ' calls/hour · rolling 1h.';

    document.getElementById('dur').textContent = Math.round(snap.avgDurationMs) + ' ms';

    var perTaskRows = [];
    for (var t in snap.perTask) {
      if (!Object.prototype.hasOwnProperty.call(snap.perTask, t)) continue;
      var r = snap.perTask[t];
      perTaskRows.push({ task: t, local: r.local, claude: r.claude, cache: r.cache,
                         total: r.local + r.claude + r.cache });
    }
    perTaskRows.sort(function (a, b) { return b.total - a.total; });

    var top3El = document.getElementById('top3');
    if (perTaskRows.length === 0) {
      top3El.innerHTML = '<div class="sub">no calls recorded yet</div>';
    } else {
      var html = '';
      for (var i = 0; i < Math.min(3, perTaskRows.length); i++) {
        var row = perTaskRows[i];
        var localPct = row.total === 0 ? 0 : (row.local / row.total * 100);
        var cachePct = row.total === 0 ? 0 : (row.cache / row.total * 100);
        var claudePct = row.total === 0 ? 0 : (row.claude / row.total * 100);
        html += '<div class="row"><span class="k">' + escapeHtml(row.task) + '</span>'
              + '<span class="v">' + row.total + ' calls</span></div>'
              + '<div class="bar">'
              + '<div class="local" style="width:' + localPct + '%"></div>'
              + '<div class="cache" style="width:' + cachePct + '%"></div>'
              + '<div class="claude" style="width:' + claudePct + '%"></div>'
              + '</div>';
      }
      top3El.innerHTML = html;
    }

    var perTaskEl = document.getElementById('pertask');
    if (perTaskRows.length === 0) {
      perTaskEl.innerHTML = '<div class="sub">no calls recorded yet</div>';
    } else {
      var ptHtml = '';
      for (var j = 0; j < perTaskRows.length; j++) {
        var r2 = perTaskRows[j];
        var localStr = r2.local + ' L';
        var claudeStr = r2.claude + ' C';
        var cacheStr = r2.cache + ' $';
        ptHtml += '<div class="row"><span class="k">' + escapeHtml(r2.task) + '</span>'
                + '<span class="v">' + localStr + ' / '
                + '<span class="claude">' + claudeStr + '</span> / '
                + '<span class="cache">' + cacheStr + '</span></span>'
                + '</div>';
      }
      perTaskEl.innerHTML = ptHtml;
    }
  }

  function escapeHtml(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
                    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  function tick() {
    fetch('/metrics', { cache: 'no-store' })
      .then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.text();
      })
      .then(function (text) { render(parseMetrics(text)); })
      .catch(function (e) {
        err.textContent = 'fetch /metrics failed: ' + e.message + ' (retrying in ' + (POLL_MS/1000) + 's)';
        err.classList.add('on');
      });
  }

  tick();
  setInterval(tick, POLL_MS);
}());
</script>
</body>
</html>
`;

/**
 * Return the dashboard HTML. Static (no per-request data) because the
 * page polls `/metrics` client-side every 5 s. Exported as a function
 * so future variants (per-host, theming) can shape the response.
 */
export function dashboardHtml(): string {
  return DASHBOARD_HTML;
}
