/**
 * Tests for the Drizzle migration breakpoint linter.
 *
 * Coverage:
 *   1. parseSql tokenizer correctness for: simple statements, comments,
 *      single-quoted strings with `''` escapes, double-quoted identifiers
 *      with `""` escapes, block comments, dollar-quoted Postgres bodies.
 *   2. lintMigrations against three fixture dirs (clean / bad / pg).
 *   3. Adversarial: empty file, single-statement file, missing journal,
 *      partial breakpoints (some present but not enough).
 *   4. exitCodeFor severity mapping.
 *
 * The "would have caught PR #287" assertion is the central regression
 * test. The bad fixture `0000_multi_no_breakpoint.sql` is structurally
 * identical to the file that broke at PR #285 / #287.
 */

import { describe, it, expect } from 'vitest';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  parseSql,
  lintMigrations,
  loadJournal,
  discoverMigrationRoots,
  exitCodeFor,
} from '../src/index.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FIX = path.join(__dirname, 'fixtures');

describe('parseSql tokenizer', () => {
  it('counts a single statement', () => {
    const r = parseSql('CREATE TABLE foo (id TEXT);');
    expect(r.statementCount).toBe(1);
    expect(r.breakpointCount).toBe(0);
  });

  it('counts multiple statements', () => {
    const r = parseSql('CREATE TABLE a (id TEXT);\nCREATE TABLE b (id TEXT);');
    expect(r.statementCount).toBe(2);
  });

  it('ignores semicolons inside line comments', () => {
    const r = parseSql('-- one ; two ; three\nCREATE TABLE foo (id TEXT);');
    expect(r.statementCount).toBe(1);
  });

  it('ignores semicolons inside block comments', () => {
    const r = parseSql('/* one ; two ; three */\nCREATE TABLE foo (id TEXT);');
    expect(r.statementCount).toBe(1);
  });

  it("ignores semicolons inside single-quoted strings (with '' escape)", () => {
    const r = parseSql(`INSERT INTO t VALUES ('a;b''c;d');`);
    expect(r.statementCount).toBe(1);
  });

  it('ignores semicolons inside double-quoted identifiers (with "" escape)', () => {
    const r = parseSql(`SELECT "weird;name""with;quotes" FROM t;`);
    expect(r.statementCount).toBe(1);
  });

  it('counts breakpoint markers', () => {
    const src = [
      'CREATE TABLE a (id TEXT);',
      '--> statement-breakpoint',
      'CREATE TABLE b (id TEXT);',
      '--> statement-breakpoint',
      'CREATE TABLE c (id TEXT);',
    ].join('\n');
    const r = parseSql(src);
    expect(r.statementCount).toBe(3);
    expect(r.breakpointCount).toBe(2);
  });

  it('tolerates whitespace around the breakpoint marker', () => {
    const r = parseSql('CREATE TABLE a (id TEXT);\n   -->   statement-breakpoint   \nCREATE TABLE b (id TEXT);');
    expect(r.breakpointCount).toBe(1);
  });

  it('matches breakpoint marker INLINE at end of statement (Drizzle ALTER TABLE shape)', () => {
    // This is the shape generated by `drizzle-kit generate` for ALTER
    // TABLE migrations. Without inline-marker support the linter false-
    // positives on every Drizzle-generated migration.
    const src = [
      'ALTER TABLE foo ADD col_a TEXT;--> statement-breakpoint',
      'ALTER TABLE foo ADD col_b TEXT;--> statement-breakpoint',
      'ALTER TABLE foo ADD col_c TEXT;',
    ].join('\n');
    const r = parseSql(src);
    expect(r.statementCount).toBe(3);
    expect(r.breakpointCount).toBe(2);
  });

  it('handles dollar-quoted Postgres bodies (semicolons inside body do not count)', () => {
    const src = [
      'CREATE FUNCTION f() RETURNS INT AS $$',
      '  DECLARE x INT;',
      '  BEGIN x := 1; RETURN x; END;',
      '$$ LANGUAGE plpgsql;',
      '--> statement-breakpoint',
      'CREATE TABLE t (id INT);',
    ].join('\n');
    const r = parseSql(src);
    expect(r.statementCount).toBe(2);
    expect(r.breakpointCount).toBe(1);
  });

  it('handles tagged dollar-quotes ($body$...$body$)', () => {
    const src = [
      "CREATE FUNCTION f() RETURNS TEXT AS $body$ SELECT 'a;b'; $body$ LANGUAGE sql;",
      '--> statement-breakpoint',
      'CREATE TABLE t (id INT);',
    ].join('\n');
    const r = parseSql(src);
    expect(r.statementCount).toBe(2);
  });

  it('reports correct line numbers for breakpoints', () => {
    const src = ['line1;', '--> statement-breakpoint', 'line3;'].join('\n');
    const r = parseSql(src);
    expect(r.breakpointLines).toEqual([2]);
  });

  it('handles empty input', () => {
    const r = parseSql('');
    expect(r.statementCount).toBe(0);
    expect(r.breakpointCount).toBe(0);
  });

  it('handles whitespace-only input', () => {
    const r = parseSql('   \n  \t  \n');
    expect(r.statementCount).toBe(0);
  });

  it('does not count semicolons inside parentheses (defensive)', () => {
    // SQL doesn't legitimately have bare ; inside parens, but the
    // tokeniser is defensive against malformed input.
    const r = parseSql('SELECT (;) FROM t;');
    expect(r.statementCount).toBe(1);
  });

  it('handles backtick-quoted identifiers (MySQL flavor)', () => {
    const r = parseSql('SELECT `weird;name` FROM t;');
    expect(r.statementCount).toBe(1);
  });

  it('handles bracket-quoted identifiers (SQL Server flavor)', () => {
    const r = parseSql('SELECT [weird;name] FROM t;');
    expect(r.statementCount).toBe(1);
  });
});

describe('loadJournal', () => {
  it('parses a valid journal', async () => {
    const j = await loadJournal(path.join(FIX, 'migrations-clean', 'meta'));
    expect(j).not.toBeNull();
    expect(j!.entries.length).toBe(4);
    expect(j!.entries[0].tag).toBe('0000_single_statement');
  });

  it('returns null when journal is missing', async () => {
    const j = await loadJournal(path.join(FIX, 'no-such-dir'));
    expect(j).toBeNull();
  });
});

describe('lintMigrations — clean fixture (no findings)', () => {
  it('emits zero findings for a fully-compliant migrations dir', async () => {
    const findings = await lintMigrations({
      migrationsDir: path.join(FIX, 'migrations-clean'),
    });
    expect(findings).toEqual([]);
  });
});

describe('lintMigrations — bad fixture (would have caught PR #287)', () => {
  it('flags 0000_multi_no_breakpoint (the PR #287 shape)', async () => {
    const findings = await lintMigrations({
      migrationsDir: path.join(FIX, 'migrations-bad'),
    });
    const hit = findings.find((f) => f.path.endsWith('0000_multi_no_breakpoint.sql'));
    expect(hit).toBeDefined();
    expect(hit!.severity).toBe('block');
    expect(hit!.ruleId).toBe('multi-statement-without-breakpoint');
    expect(hit!.context!.statementCount).toBe(3);
    expect(hit!.context!.breakpointCount).toBe(0);
  });

  it('flags 0001_partial_breakpoints (4 stmts, 1 breakpoint — still under quota)', async () => {
    const findings = await lintMigrations({
      migrationsDir: path.join(FIX, 'migrations-bad'),
    });
    const hit = findings.find((f) => f.path.endsWith('0001_partial_breakpoints.sql'));
    expect(hit).toBeDefined();
    expect(hit!.severity).toBe('block');
    expect(hit!.context!.statementCount).toBe(4);
    expect(hit!.context!.breakpointCount).toBe(1);
  });

  it('emits a remediation hint pointing at PR #287', async () => {
    const findings = await lintMigrations({
      migrationsDir: path.join(FIX, 'migrations-bad'),
    });
    expect(findings.length).toBeGreaterThan(0);
    expect(findings[0].remediation).toContain('PR #287');
  });

  it('only scans the requested basenames when onlyBasenames is set', async () => {
    const findings = await lintMigrations({
      migrationsDir: path.join(FIX, 'migrations-bad'),
      onlyBasenames: ['0000_multi_no_breakpoint.sql'],
    });
    expect(findings.length).toBe(1);
    expect(findings[0].path.endsWith('0000_multi_no_breakpoint.sql')).toBe(true);
  });

  it('reports unreadable directory as a block-severity finding', async () => {
    const findings = await lintMigrations({
      migrationsDir: '/no/such/path/that/does/not/exist',
    });
    expect(findings.length).toBe(1);
    expect(findings[0].ruleId).toBe('migrations-dir-unreadable');
    expect(findings[0].severity).toBe('block');
  });
});

describe('lintMigrations — postgres fixture (dollar-quoted bodies)', () => {
  it('emits zero findings (dollar-quoted body is correctly skipped)', async () => {
    const findings = await lintMigrations({
      migrationsDir: path.join(FIX, 'migrations-pg'),
    });
    expect(findings).toEqual([]);
  });
});

describe('discoverMigrationRoots', () => {
  it('returns the fixture root when invoked against a fixture parent', async () => {
    // discoverMigrationRoots only knows the canonical paths; we pass a
    // non-canonical root to confirm it returns [] safely.
    const roots = await discoverMigrationRoots(FIX);
    expect(Array.isArray(roots)).toBe(true);
  });
});

describe('exitCodeFor', () => {
  it('returns 0 for empty findings', () => {
    expect(exitCodeFor([])).toBe(0);
  });
  it('returns 0 for non-block findings', () => {
    expect(
      exitCodeFor([
        { analyzer: 'x', ruleId: 'y', path: 'z', severity: 'medium', message: 'm' },
        { analyzer: 'x', ruleId: 'y', path: 'z', severity: 'high', message: 'm' },
      ]),
    ).toBe(0);
  });
  it('returns 1 if any finding is block-severity', () => {
    expect(
      exitCodeFor([
        { analyzer: 'x', ruleId: 'y', path: 'z', severity: 'medium', message: 'm' },
        { analyzer: 'x', ruleId: 'y', path: 'z', severity: 'block', message: 'm' },
      ]),
    ).toBe(1);
  });
});
