/**
 * Golden test — prakash-tiwari home page fixture.
 *
 * Hand-curated `RenderableDesign` derived from the canonical CD-ZIP source
 * at `prakash-tiwari-com-design/extracted/prakash-tiwari-com/project/pages/home.jsx`.
 * We don't run a real Babel parser here (the package is dep-free besides
 * @chiefaia/ticket-template per spec), so the fixture is a hand-extracted
 * projection of what the CD-ZIP adapter would emit. The structure matches
 * the §2.1 ID convention (PG- / SE- / WD- / ST- prefixes).
 *
 * This test exercises end-to-end correctness against a realistic shape
 * (~30+ DOM-IDs, multiple sections, shared nav + footer, asset refs, copy
 * refs) and asserts the DOM-ID manifest is stable as a snapshot.
 *
 * Operator note (atlas-mapper PR): the manifest below was generated by
 * `buildDomIdMap()` on first authoring; any future change that shifts an
 * ID will fail this test loudly, which is the correct early-warning.
 */

import { describe, it, expect } from 'vitest';
import {
  buildDomIdMap,
  buildMapper,
  diffDesigns,
  type RenderableDesign,
  type RenderableNode,
  type TicketNode,
} from '../src/index.js';

/* ────────────────────────────────────────────────────────────────── */
/* fixture                                                             */
/* ────────────────────────────────────────────────────────────────── */

const node = (
  tag: string,
  role: RenderableNode['role'],
  domId: string,
  extras: Partial<RenderableNode> = {},
): RenderableNode => ({
  tag,
  role,
  domId,
  ...extras,
});

function prakashTiwariHomeV1(): RenderableDesign {
  const homeTree: RenderableNode = node('div', 'page', 'PG-home', {
    attrs: { className: 'pt', style: { width: 1440 } },
    children: [
      // Shared nav (sticky).
      node('nav', 'shared-ref', 'shared-nav', {
        attrs: { className: 'pt-chrome-dark pt-nav-dark' },
        sharedRef: 'shared:pt-nav',
      }),
      // Hero slider.
      node('section', 'section', 'SE-home-hero', {
        attrs: { className: 'pt-band-cool' },
        children: [
          node('div', 'widget', 'WD-home-hero-rotator', {
            attrs: { className: 'rotator' },
            children: [
              node('div', 'widget', 'ST-home-hero-slide-01-caia', {
                attrs: { className: 'pt-slide' },
                children: [
                  node('h1', 'leaf', 'ST-home-hero-slide-01-headline', {
                    attrs: { className: 'pt-hero-headline' },
                    copyRefs: ['copy:slide-01-headline'],
                    resolvedStyle: { fontFamily: 'Source Serif Pro', fontSize: '104px' },
                  }),
                  node('div', 'widget', 'ST-home-hero-slide-01-stats-row', {
                    attrs: { className: 'pt-stats-row' },
                    children: [
                      node('div', 'leaf', 'ST-home-hero-slide-01-stat-01', {
                        copyRefs: ['copy:slide-01-stat-01'],
                      }),
                      node('div', 'leaf', 'ST-home-hero-slide-01-stat-02', {
                        copyRefs: ['copy:slide-01-stat-02'],
                      }),
                      node('div', 'leaf', 'ST-home-hero-slide-01-stat-03', {
                        copyRefs: ['copy:slide-01-stat-03'],
                      }),
                    ],
                  }),
                ],
              }),
            ],
          }),
        ],
      }),
      // Worked-with logo wall.
      node('section', 'section', 'SE-home-worked-with', {
        attrs: { className: 'pt-band-warm' },
        children: [
          node('div', 'widget', 'WD-home-worked-with-wall', {
            attrs: { className: 'pt-logo-wall' },
            children: [
              node('a', 'leaf', 'WD-home-worked-with-logo-cvs', { attrs: { 'data-go': '/experience' } }),
              node('a', 'leaf', 'WD-home-worked-with-logo-dollar-general', { attrs: { 'data-go': '/experience' } }),
              node('a', 'leaf', 'WD-home-worked-with-logo-autozone', { attrs: { 'data-go': '/experience' } }),
            ],
          }),
        ],
      }),
      // Certifications strip.
      node('section', 'section', 'SE-home-certifications', {
        attrs: { className: 'pt-band-cool' },
        children: [
          node('div', 'leaf', 'WD-home-certifications-heading', {
            copyRefs: ['copy:certs-heading'],
          }),
          node('div', 'widget', 'WD-home-certifications-grid', {
            attrs: { className: 'pt-certs-grid' },
            children: [
              node('a', 'leaf', 'WD-home-certifications-card-aws', {
                attrs: { className: 'pt-card-i' },
                copyRefs: ['copy:cert-aws-name'],
              }),
              node('a', 'leaf', 'WD-home-certifications-card-tog', {
                attrs: { className: 'pt-card-i' },
                copyRefs: ['copy:cert-tog-name'],
              }),
            ],
          }),
        ],
      }),
      // Brief about.
      node('section', 'section', 'SE-home-about', {
        children: [
          node('h2', 'leaf', 'WD-home-about-headline', {
            copyRefs: ['copy:about-headline'],
          }),
          node('div', 'widget', 'WD-home-about-body', {
            children: [
              node('p', 'leaf', 'WD-home-about-body-p1', {
                copyRefs: ['copy:about-p1'],
              }),
              node('p', 'leaf', 'WD-home-about-body-p2', {
                copyRefs: ['copy:about-p2'],
              }),
              node('p', 'leaf', 'WD-home-about-body-p3', {
                copyRefs: ['copy:about-p3'],
              }),
            ],
          }),
        ],
      }),
      // Featured writing.
      node('section', 'section', 'SE-home-featured-writing', {
        attrs: { className: 'pt-band-sage' },
        children: [
          node('div', 'widget', 'WD-home-featured-primary', {
            attrs: { 'data-go': '/writing/the-end-of-microservices' },
            assetRefs: ['/img/microservices-hero.jpg'],
            copyRefs: ['copy:feature-microservices-headline'],
          }),
          node('div', 'widget', 'WD-home-featured-grid', {
            children: [
              node('article', 'leaf', 'WD-home-featured-card-agent-loop', {
                copyRefs: ['copy:feature-agent-loop-headline'],
              }),
              node('article', 'leaf', 'WD-home-featured-card-non-coder', {
                copyRefs: ['copy:feature-non-coder-headline'],
              }),
              node('article', 'leaf', 'WD-home-featured-card-token-cut', {
                copyRefs: ['copy:feature-token-cut-headline'],
              }),
            ],
          }),
        ],
      }),
      // Now strip.
      node('section', 'section', 'SE-home-now', {
        attrs: { className: 'pt-band-mustard' },
        children: [
          node('p', 'leaf', 'WD-home-now-body', {
            copyRefs: ['copy:now-body'],
          }),
        ],
      }),
      // Final CTA.
      node('section', 'section', 'SE-home-newsletter-cta', {
        children: [
          node('h2', 'leaf', 'WD-home-newsletter-headline', {
            copyRefs: ['copy:newsletter-headline'],
          }),
          node('div', 'widget', 'WD-home-newsletter-form', {
            children: [
              node('input', 'leaf', 'WD-home-newsletter-input-name'),
              node('input', 'leaf', 'WD-home-newsletter-input-email'),
              node('button', 'leaf', 'WD-home-newsletter-submit', {
                attrs: { className: 'pt-btn' },
                copyRefs: ['copy:newsletter-submit-label'],
              }),
            ],
          }),
        ],
      }),
      // Shared footer.
      node('footer', 'shared-ref', 'shared-footer', {
        sharedRef: 'shared:pt-footer',
      }),
    ],
  });

  return {
    designVersionId: 'dv_prakash_home_v1',
    source: 'cd-zip',
    routes: [{ path: '/', componentTreeId: 'tree:home', title: 'Home · Prakash Tiwari' }],
    componentTrees: {
      'tree:home': { rootDomId: 'PG-home', node: homeTree },
    },
    sharedComponents: [
      {
        id: 'pt-nav',
        node: node('nav', 'shared-ref', 'shared-pt-nav-root', {
          children: [
            node('a', 'leaf', 'shared-pt-nav-logo', { attrs: { 'data-go': '/' } }),
            node('ul', 'widget', 'shared-pt-nav-links', {
              children: [
                node('a', 'leaf', 'shared-pt-nav-link-about', { attrs: { 'data-go': '/about' } }),
                node('a', 'leaf', 'shared-pt-nav-link-writing', { attrs: { 'data-go': '/writing' } }),
                node('a', 'leaf', 'shared-pt-nav-link-contact', { attrs: { 'data-go': '/contact' } }),
              ],
            }),
          ],
        }),
      },
      {
        id: 'pt-footer',
        node: node('footer', 'shared-ref', 'shared-pt-footer-root', {
          children: [
            node('div', 'leaf', 'shared-pt-footer-copyright', {
              copyRefs: ['copy:footer-copyright'],
            }),
          ],
        }),
      },
    ],
    copy: [
      { domId: 'copy:slide-01-headline', text: 'Building CAIA', locale: 'en-US' },
      { domId: 'copy:slide-01-stat-01', text: '25 years EA', locale: 'en-US' },
      { domId: 'copy:slide-01-stat-02', text: '15 engagements', locale: 'en-US' },
      { domId: 'copy:slide-01-stat-03', text: '14 industries', locale: 'en-US' },
      { domId: 'copy:certs-heading', text: 'The vocabulary I show up with.', locale: 'en-US' },
      { domId: 'copy:cert-aws-name', text: 'AWS Solutions Architect Pro', locale: 'en-US' },
      { domId: 'copy:cert-tog-name', text: 'TOGAF 9 Certified', locale: 'en-US' },
      { domId: 'copy:about-headline', text: 'The senior engineer in the room.', locale: 'en-US' },
      { domId: 'copy:about-p1', text: "I've spent a quarter century inside Fortune 50 retail and e-commerce.", locale: 'en-US' },
      { domId: 'copy:about-p2', text: 'These days I build the platform I wished I had.', locale: 'en-US' },
      { domId: 'copy:about-p3', text: "I don't write code anymore.", locale: 'en-US' },
      { domId: 'copy:feature-microservices-headline', text: 'The end of microservices, again', locale: 'en-US' },
      { domId: 'copy:feature-agent-loop-headline', text: "Why your agent loop won't converge", locale: 'en-US' },
      { domId: 'copy:feature-non-coder-headline', text: 'The non-coder operator', locale: 'en-US' },
      { domId: 'copy:feature-token-cut-headline', text: 'A 90% cut in token spend', locale: 'en-US' },
      { domId: 'copy:now-body', text: 'Closing the CAIA MVP for a YC Fall 2026 application.', locale: 'en-US' },
      { domId: 'copy:newsletter-headline', text: 'One field report, every Sunday.', locale: 'en-US' },
      { domId: 'copy:newsletter-submit-label', text: 'Join 1,200 readers', locale: 'en-US' },
      { domId: 'copy:footer-copyright', text: '© 2026 Prakash Tiwari · Edison, NJ', locale: 'en-US' },
    ],
    assets: [
      {
        path: '/img/microservices-hero.jpg',
        kind: 'image',
        alt: 'The end of microservices, again',
        contentHash: 'sha256:microservices-hero-v1',
        storageUrl: 's3://t/microservices-hero-v1.jpg',
      },
    ],
    designTokens: {
      colors: { '--ink': '#1e2a35', '--paper': '#e8efe5', '--accent': '#3d6c95' },
      fonts: { '--serif': 'Source Serif Pro', '--sans': 'Inter' },
    },
  };
}

/** Build a v2 with realistic edits — headline copy + token color change. */
function prakashTiwariHomeV2(): RenderableDesign {
  const d = prakashTiwariHomeV1();
  d.designVersionId = 'dv_prakash_home_v2';
  // Copy edit: change the about headline.
  d.copy = d.copy!.map((c) =>
    c.domId === 'copy:about-headline'
      ? { ...c, text: 'The architect in the room.' }
      : c,
  );
  // Asset rotate.
  d.assets = d.assets!.map((a) =>
    a.path === '/img/microservices-hero.jpg'
      ? { ...a, contentHash: 'sha256:microservices-hero-v2', storageUrl: 's3://t/microservices-hero-v2.jpg' }
      : a,
  );
  return d;
}

/** Hand-crafted ticket tree for the home page. */
function prakashTiwariHomeTickets(): TicketNode[] {
  return [
    {
      id: 'PG-home',
      domId: 'PG-home',
      children: [
        {
          id: 'SE-home-hero',
          domId: 'SE-home-hero',
          children: [
            {
              id: 'WD-home-hero-rotator',
              domId: 'WD-home-hero-rotator',
              children: [
                {
                  id: 'ST-home-hero-slide-01-caia',
                  domId: 'ST-home-hero-slide-01-caia',
                  children: [
                    { id: 'ST-home-hero-slide-01-headline', domId: 'ST-home-hero-slide-01-headline' },
                    {
                      id: 'ST-home-hero-slide-01-stats-row',
                      domId: 'ST-home-hero-slide-01-stats-row',
                      children: [
                        { id: 'ST-home-hero-slide-01-stat-01', domId: 'ST-home-hero-slide-01-stat-01' },
                        { id: 'ST-home-hero-slide-01-stat-02', domId: 'ST-home-hero-slide-01-stat-02' },
                        { id: 'ST-home-hero-slide-01-stat-03', domId: 'ST-home-hero-slide-01-stat-03' },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        { id: 'SE-home-worked-with', domId: 'SE-home-worked-with' },
        { id: 'SE-home-certifications', domId: 'SE-home-certifications' },
        { id: 'SE-home-about', domId: 'SE-home-about' },
        { id: 'SE-home-featured-writing', domId: 'SE-home-featured-writing' },
        { id: 'SE-home-now', domId: 'SE-home-now' },
        { id: 'SE-home-newsletter-cta', domId: 'SE-home-newsletter-cta' },
      ],
    },
  ];
}

/* ────────────────────────────────────────────────────────────────── */
/* tests                                                               */
/* ────────────────────────────────────────────────────────────────── */

describe('golden — prakash-tiwari home page', () => {
  it('emits the expected canonical DOM-ID manifest', () => {
    const map = buildDomIdMap(prakashTiwariHomeV1());
    const manifest = map.entries.map((e) => ({
      domId: e.domId,
      parentDomId: e.parentDomId,
      role: e.role,
      tag: e.tag,
      position: e.position,
      componentTreeId: e.componentTreeId,
    }));
    // Inline snapshot — concrete and human-reviewable. Any future
    // change that shifts an ID fails this loudly.
    expect(manifest).toMatchInlineSnapshot(`
      [
        {
          "componentTreeId": "tree:home",
          "domId": "PG-home",
          "parentDomId": null,
          "position": 0,
          "role": "page",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "shared-nav",
          "parentDomId": "PG-home",
          "position": 0,
          "role": "shared-ref",
          "tag": "nav",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "SE-home-hero",
          "parentDomId": "PG-home",
          "position": 1,
          "role": "section",
          "tag": "section",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-hero-rotator",
          "parentDomId": "SE-home-hero",
          "position": 0,
          "role": "widget",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "ST-home-hero-slide-01-caia",
          "parentDomId": "WD-home-hero-rotator",
          "position": 0,
          "role": "widget",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "ST-home-hero-slide-01-headline",
          "parentDomId": "ST-home-hero-slide-01-caia",
          "position": 0,
          "role": "leaf",
          "tag": "h1",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "ST-home-hero-slide-01-stats-row",
          "parentDomId": "ST-home-hero-slide-01-caia",
          "position": 1,
          "role": "widget",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "ST-home-hero-slide-01-stat-01",
          "parentDomId": "ST-home-hero-slide-01-stats-row",
          "position": 0,
          "role": "leaf",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "ST-home-hero-slide-01-stat-02",
          "parentDomId": "ST-home-hero-slide-01-stats-row",
          "position": 1,
          "role": "leaf",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "ST-home-hero-slide-01-stat-03",
          "parentDomId": "ST-home-hero-slide-01-stats-row",
          "position": 2,
          "role": "leaf",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "SE-home-worked-with",
          "parentDomId": "PG-home",
          "position": 2,
          "role": "section",
          "tag": "section",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-worked-with-wall",
          "parentDomId": "SE-home-worked-with",
          "position": 0,
          "role": "widget",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-worked-with-logo-cvs",
          "parentDomId": "WD-home-worked-with-wall",
          "position": 0,
          "role": "leaf",
          "tag": "a",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-worked-with-logo-dollar-general",
          "parentDomId": "WD-home-worked-with-wall",
          "position": 1,
          "role": "leaf",
          "tag": "a",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-worked-with-logo-autozone",
          "parentDomId": "WD-home-worked-with-wall",
          "position": 2,
          "role": "leaf",
          "tag": "a",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "SE-home-certifications",
          "parentDomId": "PG-home",
          "position": 3,
          "role": "section",
          "tag": "section",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-certifications-heading",
          "parentDomId": "SE-home-certifications",
          "position": 0,
          "role": "leaf",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-certifications-grid",
          "parentDomId": "SE-home-certifications",
          "position": 1,
          "role": "widget",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-certifications-card-aws",
          "parentDomId": "WD-home-certifications-grid",
          "position": 0,
          "role": "leaf",
          "tag": "a",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-certifications-card-tog",
          "parentDomId": "WD-home-certifications-grid",
          "position": 1,
          "role": "leaf",
          "tag": "a",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "SE-home-about",
          "parentDomId": "PG-home",
          "position": 4,
          "role": "section",
          "tag": "section",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-about-headline",
          "parentDomId": "SE-home-about",
          "position": 0,
          "role": "leaf",
          "tag": "h2",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-about-body",
          "parentDomId": "SE-home-about",
          "position": 1,
          "role": "widget",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-about-body-p1",
          "parentDomId": "WD-home-about-body",
          "position": 0,
          "role": "leaf",
          "tag": "p",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-about-body-p2",
          "parentDomId": "WD-home-about-body",
          "position": 1,
          "role": "leaf",
          "tag": "p",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-about-body-p3",
          "parentDomId": "WD-home-about-body",
          "position": 2,
          "role": "leaf",
          "tag": "p",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "SE-home-featured-writing",
          "parentDomId": "PG-home",
          "position": 5,
          "role": "section",
          "tag": "section",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-featured-primary",
          "parentDomId": "SE-home-featured-writing",
          "position": 0,
          "role": "widget",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-featured-grid",
          "parentDomId": "SE-home-featured-writing",
          "position": 1,
          "role": "widget",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-featured-card-agent-loop",
          "parentDomId": "WD-home-featured-grid",
          "position": 0,
          "role": "leaf",
          "tag": "article",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-featured-card-non-coder",
          "parentDomId": "WD-home-featured-grid",
          "position": 1,
          "role": "leaf",
          "tag": "article",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-featured-card-token-cut",
          "parentDomId": "WD-home-featured-grid",
          "position": 2,
          "role": "leaf",
          "tag": "article",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "SE-home-now",
          "parentDomId": "PG-home",
          "position": 6,
          "role": "section",
          "tag": "section",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-now-body",
          "parentDomId": "SE-home-now",
          "position": 0,
          "role": "leaf",
          "tag": "p",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "SE-home-newsletter-cta",
          "parentDomId": "PG-home",
          "position": 7,
          "role": "section",
          "tag": "section",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-newsletter-headline",
          "parentDomId": "SE-home-newsletter-cta",
          "position": 0,
          "role": "leaf",
          "tag": "h2",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-newsletter-form",
          "parentDomId": "SE-home-newsletter-cta",
          "position": 1,
          "role": "widget",
          "tag": "div",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-newsletter-input-name",
          "parentDomId": "WD-home-newsletter-form",
          "position": 0,
          "role": "leaf",
          "tag": "input",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-newsletter-input-email",
          "parentDomId": "WD-home-newsletter-form",
          "position": 1,
          "role": "leaf",
          "tag": "input",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "WD-home-newsletter-submit",
          "parentDomId": "WD-home-newsletter-form",
          "position": 2,
          "role": "leaf",
          "tag": "button",
        },
        {
          "componentTreeId": "tree:home",
          "domId": "shared-footer",
          "parentDomId": "PG-home",
          "position": 8,
          "role": "shared-ref",
          "tag": "footer",
        },
        {
          "componentTreeId": "shared:pt-footer",
          "domId": "shared-pt-footer-root",
          "parentDomId": null,
          "position": 0,
          "role": "shared-ref",
          "tag": "footer",
        },
        {
          "componentTreeId": "shared:pt-footer",
          "domId": "shared-pt-footer-copyright",
          "parentDomId": "shared-pt-footer-root",
          "position": 0,
          "role": "leaf",
          "tag": "div",
        },
        {
          "componentTreeId": "shared:pt-nav",
          "domId": "shared-pt-nav-root",
          "parentDomId": null,
          "position": 0,
          "role": "shared-ref",
          "tag": "nav",
        },
        {
          "componentTreeId": "shared:pt-nav",
          "domId": "shared-pt-nav-logo",
          "parentDomId": "shared-pt-nav-root",
          "position": 0,
          "role": "leaf",
          "tag": "a",
        },
        {
          "componentTreeId": "shared:pt-nav",
          "domId": "shared-pt-nav-links",
          "parentDomId": "shared-pt-nav-root",
          "position": 1,
          "role": "widget",
          "tag": "ul",
        },
        {
          "componentTreeId": "shared:pt-nav",
          "domId": "shared-pt-nav-link-about",
          "parentDomId": "shared-pt-nav-links",
          "position": 0,
          "role": "leaf",
          "tag": "a",
        },
        {
          "componentTreeId": "shared:pt-nav",
          "domId": "shared-pt-nav-link-writing",
          "parentDomId": "shared-pt-nav-links",
          "position": 1,
          "role": "leaf",
          "tag": "a",
        },
        {
          "componentTreeId": "shared:pt-nav",
          "domId": "shared-pt-nav-link-contact",
          "parentDomId": "shared-pt-nav-links",
          "position": 2,
          "role": "leaf",
          "tag": "a",
        },
      ]
    `);
  });

  it('binds the ticket tree to the DOM map without unbound IDs', () => {
    const map = buildDomIdMap(prakashTiwariHomeV1());
    const mapper = buildMapper(map, prakashTiwariHomeTickets());
    expect(mapper.unboundDomIds).toEqual([]);
  });

  it('descendantTickets on PG-home returns the full ticket tree in pre-order', () => {
    const map = buildDomIdMap(prakashTiwariHomeV1());
    const mapper = buildMapper(map, prakashTiwariHomeTickets());
    const ids = mapper.descendantTickets('PG-home').map((t) => t.id);
    expect(ids).toEqual([
      'PG-home',
      'SE-home-hero',
      'WD-home-hero-rotator',
      'ST-home-hero-slide-01-caia',
      'ST-home-hero-slide-01-headline',
      'ST-home-hero-slide-01-stats-row',
      'ST-home-hero-slide-01-stat-01',
      'ST-home-hero-slide-01-stat-02',
      'ST-home-hero-slide-01-stat-03',
      'SE-home-worked-with',
      'SE-home-certifications',
      'SE-home-about',
      'SE-home-featured-writing',
      'SE-home-now',
      'SE-home-newsletter-cta',
    ]);
  });

  it('nearestEnclosingTicket on a stat-card returns the stats-row ticket', () => {
    const map = buildDomIdMap(prakashTiwariHomeV1());
    const mapper = buildMapper(map, prakashTiwariHomeTickets());
    const t = mapper.nearestEnclosingTicket('ST-home-hero-slide-01-stat-02');
    expect(t?.id).toBe('ST-home-hero-slide-01-stat-02');
  });

  it('diff(v1, v2) reports copy + asset changes at the right DOM-IDs', () => {
    const d = diffDesigns(prakashTiwariHomeV1(), prakashTiwariHomeV2());
    expect(d.added).toEqual([]);
    expect(d.removed).toEqual([]);
    const headlineMod = d.modified.find((m) => m.domId === 'WD-home-about-headline');
    expect(headlineMod?.reasons).toEqual(['copy_changed']);
    const featureMod = d.modified.find((m) => m.domId === 'WD-home-featured-primary');
    expect(featureMod?.reasons).toEqual(['asset_changed']);
    // Exact count: about-headline + featured-primary = 2 modified.
    expect(d.summary.modified).toBe(2);
  });
});
