// B3 (integration-remediation-b phase 3, 2026-05-15). Fingerprint utilities
// for the run-phase dispatcher template.
//
// Motivation: prior to B3 we had ~30 per-chain `_*_run_phase.sh` scripts in
// `agent-memory/`, each ~30-90 lines but ~95% identical. When the template
// drifted (heartbeat cadence, helpers, `--max-turns`), some copies got the
// fix and some didn't, and the audit trail was silent about it. The
// fingerprint binds every generated dispatcher to the canonical template
// body so any hand-edit, partial regen, or copy-paste from a stale tree
// gets caught at dispatch time instead of producing subtly-different
// worker behaviour.
//
// Design:
//   1. The generator computes `fingerprintTemplate(templateBody)` over the
//      *normalized* template — all `{{PLACEHOLDER}}` tokens collapsed to a
//      single sentinel — and emits `# CAIA_DISPATCHER_FINGERPRINT: <hex>`
//      as the second line of the rendered script.
//   2. At dispatch time, `verifyDispatcherFingerprint(dispatcherPath,
//      templateBody)` reads the script back, recovers its embedded hash,
//      normalizes the script body the same way (placeholder lines turned
//      back into `{{__PH__}}` by matching on the bash variable assignments
//      we inject), and compares.
//   3. Wrappers (3-line `exec` scripts pointed at the canonical) carry a
//      `# CAIA_DISPATCHER_WRAPPER target=<abs-path>` marker; the verifier
//      resolves the wrapper to its target and fingerprints the target.
//
// Why SHA-256 over the *normalized* body rather than the rendered one: a
// chain-specific dispatcher and the template share the same fingerprint,
// so the generator can stamp the template's fingerprint into every
// generated copy without re-hashing per-chain. Drift detection is
// equivalent (any non-placeholder change re-hashes) and the API surface
// is simpler.

import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { isAbsolute, resolve as resolvePath } from 'node:path';

/** Marker comment line emitted by the generator. */
export const FINGERPRINT_COMMENT_PREFIX = '# CAIA_DISPATCHER_FINGERPRINT:';

/** Wrapper marker — when present, the dispatcher is a thin exec stub. */
export const WRAPPER_COMMENT_PREFIX = '# CAIA_DISPATCHER_WRAPPER target=';

/** Placeholder sentinel used by `normalizeTemplate`. */
const PLACEHOLDER_SENTINEL = '__CAIA_PH__';

/** The exact bash variable names the template assigns from placeholders. */
const TEMPLATED_VARS = [
  'CHAIN_ID',
  'PHASES_FILE',
  'CAIA_CHAIN',
  'LOG_DIR',
] as const;

/**
 * Single normalizer used for both the canonical template body AND a
 * rendered dispatcher. Goal: produce *byte-identical* canonical forms so
 * the same SHA-256 falls out either way.
 *
 * Strategy:
 *   1. Drop lines that legitimately vary per-render (fingerprint stamp,
 *      provenance comment, "Generated by … at <iso>" timestamp).
 *   2. Collapse every `{{PLACEHOLDER}}` *and* every rendered value at the
 *      same syntactic position to the sentinel `__CAIA_PH__`.
 *
 * The set of known templated positions is the four `VAR="…"` bash
 * assignments plus the leading `# <chain-id> chain` comment. Any other
 * substantive change to the script body will not normalize away and
 * therefore alters the fingerprint — which is the entire point.
 */
export function normalize(body: string): string {
  const lines = body.split('\n');
  const kept: string[] = [];
  for (let line of lines) {
    if (line.startsWith(FINGERPRINT_COMMENT_PREFIX)) continue;
    if (line.startsWith('# (chain=')) continue; // provenance comment
    if (/^# Generated by `caia-chain[^`]*` at /.test(line)) continue;

    // Replace {{X}} placeholders (template form).
    line = line.replace(/\{\{[A-Z_]+\}\}/g, PLACEHOLDER_SENTINEL);
    // Replace rendered VAR="..." values back to the sentinel (rendered form).
    for (const v of TEMPLATED_VARS) {
      line = line.replace(
        new RegExp(`^${v}="[^"\\n]*"`),
        `${v}="${PLACEHOLDER_SENTINEL}"`,
      );
    }
    // Leading chain-id comment line: `# <chain-id> chain — run-phase dispatcher`.
    if (/ chain — run-phase dispatcher$/.test(line)) {
      line = `# ${PLACEHOLDER_SENTINEL} chain — run-phase dispatcher`;
    }
    kept.push(line);
  }
  return kept.join('\n');
}

/**
 * Alias kept for backwards-compatibility with the initial design split.
 * Both flavors of normalize are now the same function.
 */
export function normalizeTemplate(body: string): string {
  return normalize(body);
}

export function normalizeRenderedDispatcher(body: string): string {
  return normalize(body);
}

/** SHA-256 over the normalized template body. Returns lowercase hex. */
export function fingerprintTemplate(templateBody: string): string {
  return createHash('sha256').update(normalizeTemplate(templateBody)).digest('hex');
}

/** SHA-256 over a rendered dispatcher's normalized body. */
export function fingerprintRenderedDispatcher(body: string): string {
  return createHash('sha256').update(normalizeRenderedDispatcher(body)).digest('hex');
}

/** Parse the `# CAIA_DISPATCHER_FINGERPRINT: <hex>` line. Returns null if absent. */
export function extractEmbeddedFingerprint(body: string): string | null {
  for (const line of body.split('\n').slice(0, 20)) {
    if (line.startsWith(FINGERPRINT_COMMENT_PREFIX)) {
      return line.slice(FINGERPRINT_COMMENT_PREFIX.length).trim();
    }
  }
  return null;
}

/** Parse the `# CAIA_DISPATCHER_WRAPPER target=<path>` marker. Returns null if absent. */
export function extractWrapperTarget(body: string): string | null {
  for (const line of body.split('\n').slice(0, 10)) {
    if (line.startsWith(WRAPPER_COMMENT_PREFIX)) {
      const target = line.slice(WRAPPER_COMMENT_PREFIX.length).trim();
      // Strip surrounding quotes if present.
      return target.replace(/^["']|["']$/g, '');
    }
  }
  return null;
}

export type FingerprintVerdict =
  | { ok: true; resolved: string; embedded: string; expected: string }
  | {
      ok: false;
      reason:
        | 'missing'
        | 'mismatch'
        | 'unreadable'
        | 'not_a_caia_dispatcher'
        | 'wrapper_target_missing';
      detail: string;
      resolved?: string;
      embedded?: string | null;
      expected?: string;
    };

export interface VerifyOptions {
  /**
   * When true, return `not_a_caia_dispatcher` instead of `missing` for
   * scripts that lack the fingerprint comment entirely. The dispatch
   * guardrail uses `strict=false` so operator-spawned ad-hoc commands
   * still run; the generator's self-check passes `strict=true`.
   */
  strict?: boolean;
}

/**
 * Verify a dispatcher script's embedded fingerprint matches `expected`.
 * Follows the `# CAIA_DISPATCHER_WRAPPER` chain (one hop, no cycles
 * possible because wrappers only target absolute paths to canonical files).
 */
export function verifyDispatcherFingerprint(
  dispatcherPath: string,
  expected: string,
  opts: VerifyOptions = {},
): FingerprintVerdict {
  const strict = opts.strict ?? false;
  let body: string;
  let resolvedPath = dispatcherPath;
  try {
    body = readFileSync(dispatcherPath, 'utf8');
  } catch (err) {
    return {
      ok: false,
      reason: 'unreadable',
      detail: `cannot read ${dispatcherPath}: ${(err as Error).message}`,
      resolved: dispatcherPath,
    };
  }

  const wrapperTarget = extractWrapperTarget(body);
  if (wrapperTarget) {
    const targetAbs = isAbsolute(wrapperTarget)
      ? wrapperTarget
      : resolvePath(dispatcherPath, '..', wrapperTarget);
    if (!existsSync(targetAbs)) {
      return {
        ok: false,
        reason: 'wrapper_target_missing',
        detail: `wrapper at ${dispatcherPath} points at ${targetAbs} which does not exist`,
        resolved: targetAbs,
      };
    }
    try {
      body = readFileSync(targetAbs, 'utf8');
      resolvedPath = targetAbs;
    } catch (err) {
      return {
        ok: false,
        reason: 'unreadable',
        detail: `wrapper target unreadable: ${(err as Error).message}`,
        resolved: targetAbs,
      };
    }
  }

  const embedded = extractEmbeddedFingerprint(body);
  if (!embedded) {
    return {
      ok: false,
      reason: strict ? 'missing' : 'not_a_caia_dispatcher',
      detail: `${resolvedPath} has no ${FINGERPRINT_COMMENT_PREFIX} comment in its first 20 lines`,
      resolved: resolvedPath,
      embedded: null,
      expected,
    };
  }

  // Check 1: script body matches its own stamped fingerprint (catches
  // post-generation hand-edits that didn't update the stamp).
  const bodyHash = fingerprintRenderedDispatcher(body);
  if (bodyHash !== embedded) {
    return {
      ok: false,
      reason: 'mismatch',
      detail: `${resolvedPath} body_hash=${bodyHash} embedded=${embedded} — script body has drifted from the embedded stamp; regenerate via \`generate-run-phase.js\``,
      resolved: resolvedPath,
      embedded,
      expected,
    };
  }

  // Check 2: stamp matches the *current* canonical template (catches
  // dispatchers generated from an old template that has since been updated).
  if (embedded !== expected) {
    return {
      ok: false,
      reason: 'mismatch',
      detail: `${resolvedPath} embedded=${embedded} expected=${expected} — dispatcher was generated from an older template; regenerate via \`generate-run-phase.js\``,
      resolved: resolvedPath,
      embedded,
      expected,
    };
  }

  return { ok: true, resolved: resolvedPath, embedded, expected };
}
