// B4 (integration-remediation-b phase 4, 2026-05-15). Fingerprint utilities
// for the launchd wake-script template — parallels dispatcher-fingerprint.ts
// for the run-phase template.
//
// Motivation: before B4 each chain had a hand-copied `*_wake.sh` (~80 LOC,
// ~95% identical). When the canonical wake.sh body drifted (new helpers,
// stall-alert thresholds, paused_until handling) the fix went into some
// chains and not others. Stamping a sha256 of the *normalized* template
// body into every generated wake script (and the optional wrapper marker)
// gives the migration tool and any future regeneration step a hard signal
// for drift instead of a silent divergence.
//
// Wake scripts are launched directly by launchd — there is no internal
// dispatch path that calls into them — so unlike the run-phase fingerprint
// there is no runtime guardrail that refuses to fire on drift. The stamp
// is consumed by `bin/migrate-wakes-to-template.js` and ad-hoc audits.

import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { isAbsolute, resolve as resolvePath } from 'node:path';

export const WAKE_FINGERPRINT_COMMENT_PREFIX = '# CAIA_WAKE_FINGERPRINT:';
export const WAKE_WRAPPER_COMMENT_PREFIX = '# CAIA_WAKE_WRAPPER target=';

const PLACEHOLDER_SENTINEL = '__CAIA_PH__';

const TEMPLATED_VARS = [
  'CHAIN_ID',
  'PHASES_FILE',
  'RUNNER_SCRIPT',
  'CAIA_CHAIN_BIN',
] as const;

const HEADER_COMMENT_RE = /^# launchd-driven wake for the .+ chain\.$/;
const ECHO_INLINE_CHAIN_ID_RE = /echo "\[\$\(ts\)\] [^"]+ watchdog wake start"/;
const WATCHDOG_LOG_LINE_RE = /^WATCHDOG_LOG="\$WATCHDOG_LOG_DIR\//;

/**
 * Single normalizer used for both the canonical template body and a
 * rendered wake script. Goal: byte-identical canonical forms so the same
 * SHA-256 falls out either way.
 *
 * Strategy:
 *   1. Drop lines that legitimately vary per-render (fingerprint stamp,
 *      provenance comment, "Generated by ... at <iso>" timestamp).
 *   2. Collapse every `{{PLACEHOLDER}}` and the rendered values at known
 *      syntactic positions to the sentinel `__CAIA_PH__`.
 *
 * Known templated positions (per `bin/templates/wake.sh.template`):
 *   - `# launchd-driven wake for the {{CHAIN_ID}} chain.` (header line)
 *   - `CHAIN_ID="{{CHAIN_ID}}"` (and 3 sibling VAR=... assignments)
 *   - `WATCHDOG_LOG="$WATCHDOG_LOG_DIR/{{LOG_SLUG}}_$(date ...).log"`
 *   - `echo "[$(ts)] {{CHAIN_ID}} watchdog wake start" >> "$WATCHDOG_LOG"`
 *
 * Any other substantive change to the script body does not normalize away
 * and therefore alters the fingerprint — which is the entire point.
 */
export function normalize(body: string): string {
  const lines = body.split('\n');
  const kept: string[] = [];
  for (let line of lines) {
    if (line.startsWith(WAKE_FINGERPRINT_COMMENT_PREFIX)) continue;
    if (line.startsWith('# (chain=')) continue;
    if (/^# Generated by `caia-chain[^`]*` at /.test(line)) continue;

    if (HEADER_COMMENT_RE.test(line)) {
      line = `# launchd-driven wake for the ${PLACEHOLDER_SENTINEL} chain.`;
    }

    if (WATCHDOG_LOG_LINE_RE.test(line)) {
      line = `WATCHDOG_LOG="$WATCHDOG_LOG_DIR/${PLACEHOLDER_SENTINEL}_$(date -u +%Y-%m-%d).log"`;
    }

    line = line.replace(ECHO_INLINE_CHAIN_ID_RE, `echo "[$(ts)] ${PLACEHOLDER_SENTINEL} watchdog wake start"`);

    line = line.replace(/\{\{[A-Z_]+\}\}/g, PLACEHOLDER_SENTINEL);

    for (const v of TEMPLATED_VARS) {
      line = line.replace(
        new RegExp(`^${v}="[^"\\n]*"`),
        `${v}="${PLACEHOLDER_SENTINEL}"`,
      );
    }
    kept.push(line);
  }
  return kept.join('\n');
}

export function normalizeWakeTemplate(body: string): string {
  return normalize(body);
}

export function normalizeRenderedWake(body: string): string {
  return normalize(body);
}

export function fingerprintWakeTemplate(templateBody: string): string {
  return createHash('sha256').update(normalize(templateBody)).digest('hex');
}

export function fingerprintRenderedWake(body: string): string {
  return createHash('sha256').update(normalize(body)).digest('hex');
}

export function extractEmbeddedWakeFingerprint(body: string): string | null {
  for (const line of body.split('\n').slice(0, 20)) {
    if (line.startsWith(WAKE_FINGERPRINT_COMMENT_PREFIX)) {
      return line.slice(WAKE_FINGERPRINT_COMMENT_PREFIX.length).trim();
    }
  }
  return null;
}

export function extractWakeWrapperTarget(body: string): string | null {
  for (const line of body.split('\n').slice(0, 10)) {
    if (line.startsWith(WAKE_WRAPPER_COMMENT_PREFIX)) {
      const target = line.slice(WAKE_WRAPPER_COMMENT_PREFIX.length).trim();
      return target.replace(/^["']|["']$/g, '');
    }
  }
  return null;
}

export type WakeFingerprintVerdict =
  | { ok: true; resolved: string; embedded: string; expected: string }
  | {
      ok: false;
      reason:
        | 'missing'
        | 'mismatch'
        | 'unreadable'
        | 'not_a_caia_wake'
        | 'wrapper_target_missing';
      detail: string;
      resolved?: string;
      embedded?: string | null;
      expected?: string;
    };

export interface VerifyWakeOptions {
  strict?: boolean;
}

/**
 * Verify a wake script's embedded fingerprint matches `expected`. Follows
 * the `# CAIA_WAKE_WRAPPER target=` chain (one hop).
 */
export function verifyWakeFingerprint(
  wakePath: string,
  expected: string,
  opts: VerifyWakeOptions = {},
): WakeFingerprintVerdict {
  const strict = opts.strict ?? false;
  let body: string;
  let resolvedPath = wakePath;
  try {
    body = readFileSync(wakePath, 'utf8');
  } catch (err) {
    return {
      ok: false,
      reason: 'unreadable',
      detail: `cannot read ${wakePath}: ${(err as Error).message}`,
      resolved: wakePath,
    };
  }

  const wrapperTarget = extractWakeWrapperTarget(body);
  if (wrapperTarget) {
    const targetAbs = isAbsolute(wrapperTarget)
      ? wrapperTarget
      : resolvePath(wakePath, '..', wrapperTarget);
    if (!existsSync(targetAbs)) {
      return {
        ok: false,
        reason: 'wrapper_target_missing',
        detail: `wake wrapper at ${wakePath} points at ${targetAbs} which does not exist`,
        resolved: targetAbs,
      };
    }
    try {
      body = readFileSync(targetAbs, 'utf8');
      resolvedPath = targetAbs;
    } catch (err) {
      return {
        ok: false,
        reason: 'unreadable',
        detail: `wake wrapper target unreadable: ${(err as Error).message}`,
        resolved: targetAbs,
      };
    }
  }

  const embedded = extractEmbeddedWakeFingerprint(body);
  if (!embedded) {
    return {
      ok: false,
      reason: strict ? 'missing' : 'not_a_caia_wake',
      detail: `${resolvedPath} has no ${WAKE_FINGERPRINT_COMMENT_PREFIX} comment in its first 20 lines`,
      resolved: resolvedPath,
      embedded: null,
      expected,
    };
  }

  const bodyHash = fingerprintRenderedWake(body);
  if (bodyHash !== embedded) {
    return {
      ok: false,
      reason: 'mismatch',
      detail: `${resolvedPath} body_hash=${bodyHash} embedded=${embedded} — wake script has drifted from its embedded stamp; regenerate via \`generate-wake.js\``,
      resolved: resolvedPath,
      embedded,
      expected,
    };
  }
  if (embedded !== expected) {
    return {
      ok: false,
      reason: 'mismatch',
      detail: `${resolvedPath} embedded=${embedded} expected=${expected} — wake was generated from an older template; regenerate via \`generate-wake.js\``,
      resolved: resolvedPath,
      embedded,
      expected,
    };
  }

  return { ok: true, resolved: resolvedPath, embedded, expected };
}
