-- Seed all predefined domains (idempotent via INSERT OR IGNORE)
INSERT OR IGNORE INTO `domains` (`slug`, `name`, `description`, `color`, `icon`, `created_at`) VALUES
  ('conductor-architecture', 'Conductor Architecture', 'Conductor''s own backend, DB, WS, API evolution', '#4A90D9', '🎼', datetime('now')),
  ('conductor-dashboard-features', 'Conductor Dashboard', 'Conductor UI/UX, routes, widgets, dashboard features', '#7B68EE', '📊', datetime('now')),
  ('framework-scaffold', 'Framework Scaffold', 'Multi-repo/monorepo pattern, site-template, ADRs', '#20B2AA', '🏗️', datetime('now')),
  ('image-provider', 'Image Provider', 'Image provider plugin package', '#FF6B6B', '🖼️', datetime('now')),
  ('cast-bridge', 'Cast Bridge', 'Cast bridge plugin package', '#FF8C42', '🌉', datetime('now')),
  ('dev-inspector', 'Dev Inspector', 'Dev inspector plugin package', '#FFD93D', '🔍', datetime('now')),
  ('backend-core', 'Backend Core', 'Backend core plugin package', '#6BCB77', '⚙️', datetime('now')),
  ('content-engine', 'Content Engine', 'Content engine plugin package', '#4D96FF', '📄', datetime('now')),
  ('integrity-check', 'Integrity Check', 'Integrity check plugin package', '#C77DFF', '✅', datetime('now')),
  ('seo-program', 'SEO Program', 'SEO program plugin package', '#FF6B9D', '🔎', datetime('now')),
  ('analytics', 'Analytics', 'Analytics plugin — GA4, Cloudflare Web Analytics', '#06D6A0', '📈', datetime('now')),
  ('content', 'Content', 'Editorial, publications, authoring workflows', '#FFB347', '✍️', datetime('now')),
  ('accessibility', 'Accessibility', 'WCAG 2.2 AA+ compliance, axe-core, screen-reader work', '#A8DADC', '♿', datetime('now')),
  ('seo', 'SEO', 'Audits, remediation, keyword and content gap analysis', '#F4A261', '🎯', datetime('now')),
  ('marketing', 'Marketing', 'Campaigns, brand strategy, positioning', '#E76F51', '📢', datetime('now')),
  ('martech', 'Martech', 'Analytics stack, GA4, attribution, email marketing', '#264653', '📊', datetime('now')),
  ('gameplay', 'Gameplay', 'Poker engine, roulette engine, /play pages', '#2A9D8F', '🃏', datetime('now')),
  ('theming-branding', 'Theming & Branding', 'Visual design, brand lock, design tokens', '#E9C46A', '🎨', datetime('now')),
  ('media-imagery', 'Media & Imagery', 'Image acquisition, R2 storage, OG images, no-minors enforcement', '#F4D03F', '📸', datetime('now')),
  ('deployment-devops', 'Deployment & DevOps', 'Cloudflare Pages, Wrangler, CI/CD pipelines', '#85C1E9', '🚀', datetime('now')),
  ('testing-qa', 'Testing & QA', 'E2E tests, integrity gates, axe-core, Playwright', '#A9DFBF', '🧪', datetime('now')),
  ('data-backend', 'Data & Backend', 'Supabase, schema design, auth, persistence', '#FAD7A0', '🗄️', datetime('now')),
  ('security', 'Security', 'Secrets management, tokens, hook enforcement', '#F1948A', '🔒', datetime('now')),
  ('uncategorized', 'Uncategorized', 'Fallback domain for unclassified work', '#718096', '📌', datetime('now'));
