/**
 * Write the wrapper artifacts:
 *   - training-metadata.json   (CAIA-side context for Phase 3 + Phase 4)
 *   - Modelfile                (Ollama scaffold — Phase 3 deploys)
 *
 * The Modelfile FROM directive uses the `baseModelOllamaTag` config
 * value (e.g. `qwen2.5-coder:7b`) so the generated file is portable to
 * the operator's Ollama install without further substitution.
 */

import * as path from 'node:path';
import { createHash } from 'node:crypto';
import type {
  FsAccess,
  ResolvedTrainingConfig,
  TrainingMetadata
} from './types.js';

export interface MetadataInput {
  cfg: ResolvedTrainingConfig;
  adapterPath: string;
  corpusManifestPath: string;
  corpusManifestSha256: string;
  trainCount: number;
  validCount: number;
  testCount: number;
  argv: string[];
  exitCode: number;
  elapsedMs: number;
  timedOut: boolean;
  host: { model?: string; memBytes?: number; arch?: string };
  git?: { branch?: string; sha?: string; dirty?: boolean };
  warnings: string[];
}

export class MetadataWriter {
  constructor(private readonly fs: FsAccess, private readonly clock: () => Date) {}

  /**
   * Write training-metadata.json + Modelfile. Returns the metadata that
   * was written, for inclusion in TrainResult.
   */
  write(input: MetadataInput): { metadata: TrainingMetadata; modelfilePath: string; metadataPath: string } {
    const metadata: TrainingMetadata = {
      version: 1,
      generatedAt: this.clock().toISOString(),
      trainerVersion: '@chiefaia/apprentice-training@0.1.0',
      corpusManifestPath: input.corpusManifestPath,
      corpusManifestSha256: input.corpusManifestSha256,
      corpusTotals: {
        samplesUsed: input.trainCount + input.validCount + input.testCount,
        trainCount: input.trainCount,
        validCount: input.validCount,
        testCount: input.testCount
      },
      baseModel: input.cfg.baseModel,
      baseModelOllamaTag: input.cfg.baseModelOllamaTag,
      loraConfig: input.cfg.loraConfig,
      subprocess: {
        argv: input.argv,
        exitCode: input.exitCode,
        elapsedMs: input.elapsedMs,
        timedOut: input.timedOut,
        host: input.host
      },
      configSha256: configSha256(input.cfg),
      warnings: input.warnings
    };
    if (input.git !== undefined) metadata.git = input.git;

    const metadataPath = path.join(input.adapterPath, 'training-metadata.json');
    this.fs.writeFile(metadataPath, JSON.stringify(metadata, null, 2) + '\n');

    const modelfilePath = path.join(input.adapterPath, 'Modelfile');
    this.fs.writeFile(modelfilePath, renderModelfile(input.cfg));

    return { metadata, modelfilePath, metadataPath };
  }
}

/**
 * Hash the resolved config — for cross-run identity tracking. Excludes
 * test seams (subprocessRunner / fs / clock / evalHarness) and absolute
 * paths so the same config across hosts produces the same hash.
 */
export function configSha256(cfg: ResolvedTrainingConfig): string {
  const stable = {
    baseModel: cfg.baseModel,
    baseModelOllamaTag: cfg.baseModelOllamaTag,
    pythonBinaryPath: cfg.pythonBinaryPath,
    mlxLmModule: cfg.mlxLmModule,
    loraConfig: cfg.loraConfig,
    trainSplitFraction: cfg.trainSplitFraction,
    validSplitFraction: cfg.validSplitFraction,
    testSplitFraction: cfg.testSplitFraction,
    splitSeed: cfg.splitSeed,
    minSamplesToTrain: cfg.minSamplesToTrain,
    cloudGpuEnabled: cfg.cloudGpuEnabled
  };
  return createHash('sha256').update(JSON.stringify(stable)).digest('hex');
}

/**
 * Render the Ollama Modelfile scaffold. Phase 3 (serving) consumes it
 * via `ollama create apprentice-v1 -f Modelfile`.
 *
 * The SYSTEM block intentionally does NOT bake a project-specific primer
 * here — Phase 3's runtime overlays the live primer. Keeping the scaffold
 * model-only avoids drift between training time and serving time.
 */
function renderModelfile(cfg: ResolvedTrainingConfig): string {
  return [
    `# Apprentice adapter Modelfile — generated by @chiefaia/apprentice-training`,
    `# Phase 3 (serving) consumes this via 'ollama create apprentice-v1 -f Modelfile'.`,
    ``,
    `FROM ${cfg.baseModelOllamaTag}`,
    `ADAPTER ./adapters.safetensors`,
    ``,
    `PARAMETER temperature 0.2`,
    `PARAMETER top_p 0.9`,
    ``
  ].join('\n');
}
