-- Drizzle accepts the marker inline (end-of-statement) — common shape
-- for ALTER TABLE migrations generated by `drizzle-kit generate`.
ALTER TABLE foo ADD col_a TEXT;--> statement-breakpoint
ALTER TABLE foo ADD col_b TEXT;--> statement-breakpoint
ALTER TABLE foo ADD col_c TEXT;
