#!/usr/bin/env bash
#
# Install the Librarian CLI shims into ~/.local/bin (which is on $PATH
# per the standard Mac dev shell). The shims are tiny scripts that
# `exec node` against the package's compiled dist/ files in-place — so
# rebuilds (`pnpm -C packages/librarian build`) take effect immediately
# without re-running install.
#
# Idempotent: re-running this script overwrites the shims with the
# current package layout. Safe to run after a `git pull` that updates
# the package.
#
# Usage:
#   bash packages/librarian/scripts/install.sh
#   bash packages/librarian/scripts/install.sh --target /usr/local/bin
#   bash packages/librarian/scripts/install.sh --uninstall
#
set -euo pipefail

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_DIR="${HOME}/.local/bin"
MODE="install"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      shift
      TARGET_DIR="$1"
      shift
      ;;
    --uninstall)
      MODE="uninstall"
      shift
      ;;
    *)
      echo "unknown flag: $1" >&2
      exit 1
      ;;
  esac
done

CLIS=(
  "caia-librarian-index:cli.js"
  "caia-librarian-retrieve:retrieve-cli.js"
  "caia-librarian-prepend:prepend-cli.js"
)

if [[ "$MODE" == "uninstall" ]]; then
  for entry in "${CLIS[@]}"; do
    name="${entry%%:*}"
    rm -f "${TARGET_DIR}/${name}"
    echo "removed ${TARGET_DIR}/${name}"
  done
  exit 0
fi

# Verify dist exists; if not, point the operator at the build step
# rather than silently shimming a non-existent file.
if [[ ! -d "${PKG_DIR}/dist" ]]; then
  echo "librarian/dist not built yet. Run:" >&2
  echo "  pnpm -C packages/librarian build" >&2
  exit 2
fi

mkdir -p "${TARGET_DIR}"

NODE_BIN="$(command -v node || echo /opt/homebrew/bin/node)"
if [[ ! -x "${NODE_BIN}" ]]; then
  echo "node not found on PATH and /opt/homebrew/bin/node is not executable" >&2
  exit 2
fi

for entry in "${CLIS[@]}"; do
  name="${entry%%:*}"
  script="${entry##*:}"
  shim="${TARGET_DIR}/${name}"
  cat > "${shim}" <<EOF
#!/usr/bin/env bash
# Auto-generated by packages/librarian/scripts/install.sh — do not edit.
exec "${NODE_BIN}" "${PKG_DIR}/dist/${script}" "\$@"
EOF
  chmod +x "${shim}"
  echo "installed ${shim}"
done

echo
echo "Librarian CLIs installed. Try:"
echo "  caia-librarian-index help"
echo "  caia-librarian-index status"
echo "  echo 'a sample prompt' | caia-librarian-prepend"
