apiVersion: v1
kind: Service
metadata:
  name: nats-headless
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: cluster
spec:
  clusterIP: None
  publishNotReadyAddresses: true   # pods need to see each other during cluster bootstrap
  selector:
    app.kubernetes.io/name: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: cluster
      port: 6222
      targetPort: 6222
    - name: monitor
      port: 8222
      targetPort: 8222
