/**
 * DASH-002 — canonical URL schema redirects.
 * Source of truth: caia/docs/dashboard-url-schema.md (§4 redirect map).
 */
module.exports = [
  { source: '/prompts', destination: '/work/prompts', permanent: false },
  { source: '/prompts/:id', destination: '/work/prompts/:id', permanent: false },
  { source: '/prompts/:id/journey', destination: '/work/prompts/:id/journey', permanent: false },
  { source: '/submit', destination: '/work/submit', permanent: false },
  { source: '/queue', destination: '/work/queue', permanent: false },
  { source: '/buckets', destination: '/work/buckets', permanent: false },
  { source: '/tasks', destination: '/work/tasks', permanent: false },
  { source: '/tasks/:id', destination: '/work/tasks/:id', permanent: false },
  { source: '/stories', destination: '/work/stories', permanent: false },
  { source: '/stories/:id', destination: '/work/stories/:id', permanent: false },
  { source: '/blockers', destination: '/work/blockers', permanent: false },
  { source: '/blockers/:id', destination: '/work/blockers/:id', permanent: false },
  { source: '/requirements', destination: '/work/requirements', permanent: false },
  { source: '/requirements/:id', destination: '/work/requirements/:id', permanent: false },
  { source: '/questions', destination: '/work/questions', permanent: false },
  { source: '/questions/:id', destination: '/work/questions/:id', permanent: false },
  { source: '/suggestions', destination: '/work/suggestions', permanent: false },
  { source: '/reports/prompts', destination: '/work/prompts/reports', permanent: false },
  { source: '/timeline', destination: '/pipeline/timeline', permanent: false },
  { source: '/events', destination: '/pipeline/events', permanent: false },
  { source: '/task-runs', destination: '/pipeline/task-runs', permanent: false },
  { source: '/task-runs/:session_id', destination: '/pipeline/task-runs/:session_id', permanent: false },
  { source: '/dag', destination: '/pipeline/dag', permanent: false },
  { source: '/projects', destination: '/catalog/projects', permanent: false },
  { source: '/projects/:slug', destination: '/catalog/projects/:slug', permanent: false },
  { source: '/domains', destination: '/catalog/domains', permanent: false },
  { source: '/domains/:slug', destination: '/catalog/domains/:slug', permanent: false },
  { source: '/architecture', destination: '/catalog/architecture', permanent: false },
  { source: '/contracts', destination: '/catalog/contracts', permanent: false },
  { source: '/features', destination: '/catalog/features', permanent: false },
  { source: '/features/:id', destination: '/catalog/features/:id', permanent: false },
  { source: '/agents', destination: '/catalog/agents', permanent: false },
  { source: '/registry', destination: '/catalog/registry', permanent: false },
  { source: '/gates', destination: '/quality/gates', permanent: false },
  { source: '/tests', destination: '/quality/tests', permanent: false },
  { source: '/tests/:id', destination: '/quality/tests/:id', permanent: false },
  { source: '/completeness', destination: '/quality/completeness', permanent: false },
  { source: '/platform-status', destination: '/operations', permanent: false },
  { source: '/health/pulse', destination: '/operations/health', permanent: false },
  { source: '/observability/health', destination: '/operations/observability', permanent: false },
  { source: '/metrics', destination: '/operations/metrics', permanent: false },
  { source: '/metrics/llm', destination: '/operations/metrics/llm', permanent: false },
  { source: '/metrics/phase1', destination: '/operations/metrics/phase1', permanent: false },
  { source: '/builds', destination: '/operations/builds', permanent: false },
  { source: '/builds/:id', destination: '/operations/builds/:id', permanent: false },
  { source: '/audit', destination: '/operations/audit', permanent: false },
  { source: '/audit/:entityKind/:entityId', destination: '/operations/audit/:entityKind/:entityId', permanent: false },
  { source: '/standards', destination: '/settings/standards', permanent: false },
  { source: '/adrs', destination: '/settings/adrs', permanent: false },
  { source: '/adrs/:number', destination: '/settings/adrs/:number', permanent: false },
];
