/**
 * Stage C — FigmaSpec → Scaffold.
 *
 * Phase 1 STUB. Phase 4 will:
 *  - read `templates/site/src/app/page.tsx` from `config.scaffoldTargetTemplate`
 *  - generate a real Next.js `page.tsx` that imports the mapped components
 *  - emit a `page.config.ts` with the section list + props
 *  - place files under the new site's `src/app/<route>/` slot
 *
 * The Phase 1 stub:
 *  - emits a placeholder `page.tsx` with one TODO per frame
 *  - emits a `page.config.ts` exporting the formal-doc-derived section list
 *  - never touches the filesystem — caller materialises the files
 *
 * The shape of `Scaffold` is preserved so Phase 4 can drop in the real
 * generator without changing the public contract.
 */

import type { FigmaSpec, Scaffold, ScaffoldFile } from './types.js';
import type { VastuConfig } from './config.js';

export interface FigmaToScaffoldOptions {
  figmaSpec: FigmaSpec;
  config: VastuConfig;
}

export async function figmaToScaffold(opts: FigmaToScaffoldOptions): Promise<Scaffold> {
  const { figmaSpec } = opts;

  const pageTsx = renderStubPageTsx(figmaSpec);
  const pageConfigTs = renderStubPageConfigTs(figmaSpec);

  const files: ScaffoldFile[] = [
    { path: `src/app/${figmaSpec.meta.pageId}/page.tsx`, contents: pageTsx },
    { path: `src/app/${figmaSpec.meta.pageId}/page.config.ts`, contents: pageConfigTs }
  ];

  const notes: string[] = [];
  if (figmaSpec.unmappedSections.length > 0) {
    notes.push(
      `Stage C left ${figmaSpec.unmappedSections.length} section(s) as placeholders (no Figma mapping yet): ${figmaSpec.unmappedSections.join(', ')}.`
    );
  }
  notes.push('Phase 1 scaffold is a stub — Phase 4 will materialise real Next.js components.');

  return {
    pageId: figmaSpec.meta.pageId,
    files,
    notes
  };
}

function renderStubPageTsx(spec: FigmaSpec): string {
  const sectionTodos = spec.frames
    .map(
      (f) =>
        `      {/* TODO: render ${f.componentRef.codeConnectKey} (${f.name}) — Phase 4 */}`
    )
    .join('\n');

  return `// Auto-generated by @chiefaia/vastu Phase 1 stub. Do not edit by hand.
// Page: ${spec.pageName}
// Generated: ${spec.meta.generatedAt}

export default function Page() {
  return (
    <main>
      <h1>${spec.pageName}</h1>
${sectionTodos}
    </main>
  );
}
`;
}

function renderStubPageConfigTs(spec: FigmaSpec): string {
  const sectionEntries = spec.frames
    .map(
      (f) =>
        `  { id: ${JSON.stringify(f.meta.sectionId)}, section: ${JSON.stringify(f.componentRef.codeConnectKey)}, height: ${f.height}, props: {} }`
    )
    .join(',\n');

  return `// Auto-generated by @chiefaia/vastu Phase 1 stub.
export const pageConfig = {
  id: ${JSON.stringify(spec.meta.pageId)},
  name: ${JSON.stringify(spec.pageName)},
  sections: [
${sectionEntries}
  ]
} as const;
`;
}
