#!/usr/bin/env bash
# caia/observability/init-langfuse-secrets.sh
#
# Bootstraps caia/observability/.env.local from Vault.
#
# Behaviour:
# 1. If .env.local already exists and --force is NOT passed, exit 0
#    (idempotent — safe to run on every start).
# 2. Try Vault: read every required secret from
#    secret/caia/langfuse. If Vault is reachable AND has the
#    secrets, write .env.local and exit 0.
# 3. Otherwise: generate fresh secrets, write .env.local, AND
#    print a vault-write incantation so the operator can store
#    them back into Vault for future restarts.
#
# Reference: caia/docs/observability-langfuse.md.

set -euo pipefail

THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${THIS_DIR}/.env.local"
EXAMPLE_FILE="${THIS_DIR}/.env.example"
FORCE=0
QUIET=0

for arg in "$@"; do
  case "${arg}" in
    --force) FORCE=1 ;;
    --quiet) QUIET=1 ;;
    -h|--help)
      cat <<'EOF'
init-langfuse-secrets.sh — populate .env.local for the Langfuse stack.

Usage:
  ./init-langfuse-secrets.sh [--force] [--quiet]

  --force   Overwrite an existing .env.local.
  --quiet   Suppress informational logging.

Sources of truth (in priority order):
  1. Vault path secret/caia/langfuse  (preferred)
  2. Locally generated random values (fallback)

Required Vault fields (when Vault is the source):
  postgres_password, clickhouse_password, redis_password,
  minio_root_password, encryption_key, salt, nextauth_secret,
  admin_email, admin_password,
  init_project_public_key (optional), init_project_secret_key (optional)
EOF
      exit 0
      ;;
  esac
done

log() { [[ "${QUIET}" -eq 1 ]] || echo "$@" >&2; }
die() { echo "✗ $*" >&2; exit 1; }

if [[ -f "${ENV_FILE}" && "${FORCE}" -ne 1 ]]; then
  log "→ ${ENV_FILE} already exists; pass --force to overwrite. (no-op)"
  exit 0
fi

# ─── Vault path ───────────────────────────────────────────────────
# Two ways to reach Vault:
#   (a) Locally — VAULT_ADDR + VAULT_TOKEN env vars set.
#   (b) Via the stolution remote — ssh stolution + docker exec.
# We try (a) first; (b) is the fallback because the Mac developer
# may not have a Vault CLI installed locally.

vault_kv_get() {
  local field="$1"
  if [[ -n "${VAULT_ADDR:-}" && -n "${VAULT_TOKEN:-}" ]] && command -v vault >/dev/null 2>&1; then
    vault kv get -field="${field}" secret/caia/langfuse 2>/dev/null && return 0
  fi
  if command -v ssh >/dev/null 2>&1; then
    ssh -o BatchMode=yes -o ConnectTimeout=5 stolution \
      "docker exec stolution-vault sh -c 'vault kv get -field=${field} secret/caia/langfuse 2>/dev/null'" \
      2>/dev/null && return 0
  fi
  return 1
}

# Try to read every secret. Empty string = missing.
log "→ checking Vault at secret/caia/langfuse"
PG_PW=$(vault_kv_get postgres_password || echo "")
CH_PW=$(vault_kv_get clickhouse_password || echo "")
REDIS_PW=$(vault_kv_get redis_password || echo "")
MINIO_PW=$(vault_kv_get minio_root_password || echo "")
ENCRYPTION_KEY=$(vault_kv_get encryption_key || echo "")
SALT=$(vault_kv_get salt || echo "")
NEXTAUTH_SECRET=$(vault_kv_get nextauth_secret || echo "")
ADMIN_EMAIL=$(vault_kv_get admin_email || echo "")
ADMIN_PW=$(vault_kv_get admin_password || echo "")
INIT_PUB=$(vault_kv_get init_project_public_key || echo "")
INIT_SEC=$(vault_kv_get init_project_secret_key || echo "")

VAULT_HAD_ALL=1
for v in "${PG_PW}" "${CH_PW}" "${REDIS_PW}" "${MINIO_PW}" "${ENCRYPTION_KEY}" "${SALT}" "${NEXTAUTH_SECRET}" "${ADMIN_EMAIL}" "${ADMIN_PW}"; do
  [[ -z "${v}" ]] && VAULT_HAD_ALL=0
done

if [[ "${VAULT_HAD_ALL}" -eq 1 ]]; then
  log "✓ all 9 required secrets present in Vault"
else
  log "→ Vault read partial / unreachable; generating fresh values for missing fields"
fi

# ─── Generate fresh values for any missing field ─────────────────
gen_password() { openssl rand -base64 32 | tr -d '/+=' | head -c 24; }
gen_hex32()    { openssl rand -hex 32; }

[[ -z "${PG_PW}" ]]              && PG_PW=$(gen_password)
[[ -z "${CH_PW}" ]]              && CH_PW=$(gen_password)
[[ -z "${REDIS_PW}" ]]           && REDIS_PW=$(gen_password)
[[ -z "${MINIO_PW}" ]]           && MINIO_PW=$(gen_password)
[[ -z "${ENCRYPTION_KEY}" ]]     && ENCRYPTION_KEY=$(gen_hex32)
[[ -z "${SALT}" ]]               && SALT=$(openssl rand -base64 32)
[[ -z "${NEXTAUTH_SECRET}" ]]    && NEXTAUTH_SECRET=$(openssl rand -base64 32)
[[ -z "${ADMIN_EMAIL}" ]]        && ADMIN_EMAIL="ops@caia.local"
[[ -z "${ADMIN_PW}" ]]           && ADMIN_PW=$(gen_password)
# Init project keys are optional.
[[ -z "${INIT_PUB}" ]]           && INIT_PUB=""
[[ -z "${INIT_SEC}" ]]           && INIT_SEC=""

# ─── Write .env.local ─────────────────────────────────────────────
umask 077
cat > "${ENV_FILE}" <<EOF
# Generated by init-langfuse-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT. .gitignored.
LANGFUSE_PORT=3001
LANGFUSE_POSTGRES_DB=langfuse
LANGFUSE_POSTGRES_USER=langfuse
LANGFUSE_POSTGRES_PASSWORD=${PG_PW}
LANGFUSE_CLICKHOUSE_DB=default
LANGFUSE_CLICKHOUSE_USER=clickhouse
LANGFUSE_CLICKHOUSE_PASSWORD=${CH_PW}
LANGFUSE_REDIS_PASSWORD=${REDIS_PW}
LANGFUSE_MINIO_ROOT_USER=langfuse-minio-admin
LANGFUSE_MINIO_ROOT_PASSWORD=${MINIO_PW}
LANGFUSE_ENCRYPTION_KEY=${ENCRYPTION_KEY}
LANGFUSE_SALT=${SALT}
LANGFUSE_NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
LANGFUSE_INIT_ORG_ID=caia
LANGFUSE_INIT_ORG_NAME=CAIA
LANGFUSE_INIT_PROJECT_ID=caia-orchestrator
LANGFUSE_INIT_PROJECT_NAME=CAIA Orchestrator
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${INIT_PUB}
LANGFUSE_INIT_PROJECT_SECRET_KEY=${INIT_SEC}
LANGFUSE_INIT_USER_EMAIL=${ADMIN_EMAIL}
LANGFUSE_INIT_USER_NAME=CAIA Operator
LANGFUSE_INIT_USER_PASSWORD=${ADMIN_PW}
EOF
chmod 600 "${ENV_FILE}"
log "✓ wrote ${ENV_FILE} (mode 600)"

# ─── If Vault was missing fields, print a write-back hint ────────
if [[ "${VAULT_HAD_ALL}" -ne 1 ]]; then
  cat <<EOF >&2

  ┌─────────────────────────────────────────────────────────────┐
  │  One-time Vault provisioning                                │
  ├─────────────────────────────────────────────────────────────┤
  │  Some fields were missing in Vault and have been generated  │
  │  locally. To persist them so future restarts pick them up:  │
  │                                                             │
  │  ssh stolution "docker exec -i stolution-vault \\           │
  │    vault kv put secret/caia/langfuse \\                     │
  │      postgres_password='${PG_PW}' \\                        │
  │      clickhouse_password='${CH_PW}' \\                      │
  │      redis_password='${REDIS_PW}' \\                        │
  │      minio_root_password='${MINIO_PW}' \\                   │
  │      encryption_key='${ENCRYPTION_KEY}' \\                  │
  │      salt='${SALT}' \\                                      │
  │      nextauth_secret='${NEXTAUTH_SECRET}' \\                │
  │      admin_email='${ADMIN_EMAIL}' \\                        │
  │      admin_password='${ADMIN_PW}'"                          │
  │                                                             │
  │  Admin login URL:  http://localhost:3001                    │
  │  Admin email:      ${ADMIN_EMAIL}                           │
  │  Admin password:   (see .env.local)                         │
  └─────────────────────────────────────────────────────────────┘

EOF
fi
