/**
 * Generate `caia/docs/ai-ml-architecture-conventions.md`.
 */

import { MODEL_CATALOG, ROUTING_RULES } from '@chiefaia/local-llm-router';

import { ASSERTION_TYPES } from './knowledge/eval-methodology.js';
import { PROMPT_PATTERN_RULES } from './knowledge/prompt-patterns.js';

export interface GenerateConventionDocInput {
  readonly generatedAtIso: string;
  readonly canonicalSuitePath: string;
}

export function generateConventionDoc(
  input: GenerateConventionDocInput
): string {
  const lines: string[] = [];

  lines.push('# AI/ML Architecture Conventions (CAIA)');
  lines.push('');
  lines.push(
    '> Auto-generated by `@chiefaia/aiml-architect` — the AI/ML Architect Agent. ' +
      'Do not hand-edit; regenerate via `caia-aiml-architect convention`.'
  );
  lines.push('');
  lines.push(`Generated at: ${input.generatedAtIso}`);
  lines.push('');
  lines.push('## 1. Model routing decision tree');
  lines.push('');
  lines.push(
    'Per `@chiefaia/local-llm-router`'+ '`s `routing-config.ts`, the canonical ' +
      'rule per task category is:'
  );
  lines.push('');
  lines.push(
    '| Task category | Local model | Claude model | Use local? | Max tokens | Cost (Claude) |'
  );
  lines.push('|---|---|---|---|---|---|');
  const sortedRules = [...ROUTING_RULES].sort((a, b) =>
    a.taskType.localeCompare(b.taskType)
  );
  for (const r of sortedRules) {
    lines.push(
      `| \`${r.taskType}\` | \`${r.localModel}\` | \`${r.claudeModel ?? '—'}\` | ` +
        `${r.useLocal ? '✅' : '❌'} | ${r.maxTokens} | ${r.estimatedCostClaude} |`
    );
  }
  lines.push('');
  lines.push('## 2. Local model catalog');
  lines.push('');
  lines.push('| Tag | Params | RAM (GB) | Disk (GB) | Role | Endpoint |');
  lines.push('|---|---|---|---|---|---|');
  const sortedModels = [...MODEL_CATALOG].sort((a, b) =>
    a.tag.localeCompare(b.tag)
  );
  for (const m of sortedModels) {
    lines.push(
      `| \`${m.tag}\` | ${m.params} | ${m.runtimeRamGB} | ${m.diskSizeGB} | ` +
        `${m.role} | ${m.endpoint} |`
    );
  }
  lines.push('');
  lines.push('## 3. Prompt engineering patterns');
  lines.push('');
  lines.push(
    'The architect reviews every prompt template against these patterns. ' +
      'Findings carry severity `info` / `warn` / `error`; only `error` is blocking.'
  );
  lines.push('');
  lines.push('| Pattern | Weight | When it applies |');
  lines.push('|---|---|---|');
  const sortedPatterns = [...PROMPT_PATTERN_RULES].sort((a, b) =>
    b.weight === a.weight ? a.pattern.localeCompare(b.pattern) : b.weight - a.weight
  );
  for (const p of sortedPatterns) {
    lines.push(`| \`${p.pattern}\` | ${p.weight.toFixed(2)} | (rule-driven; see source) |`);
  }
  lines.push('');
  lines.push('## 4. DSPy compilation policy');
  lines.push('');
  lines.push(
    '`reviewPromptPattern()` recommends DSPy compilation when 2 of 3 signals hold:'
  );
  lines.push('');
  lines.push('1. **High-frequency call** (>1k calls/day) — compile cost amortises within a day.');
  lines.push('2. **Reliability-sensitive** (>99% required accuracy) — manual prompts plateau ~95-97%.');
  lines.push('3. **Cross-model portable** — DSPy compiles per-model; swapping is mechanically clean.');
  lines.push('');
  lines.push(
    'The orchestrator decides when to actually compile; the architect emits the recommendation only.'
  );
  lines.push('');
  lines.push('## 5. Eval methodology');
  lines.push('');
  lines.push('CAIA runs **two** eval substrates:');
  lines.push('');
  lines.push('- **Promptfoo** (already shipped via `@chiefaia/prompt-evals`) — fast YAML/CLI gate, red-team plugins.');
  lines.push('- **DeepEval** (optional, subprocess-bridged) — pytest-style metric scoring with G-Eval, hallucination, faithfulness.');
  lines.push('');
  lines.push('### 5a. Assertion type routing');
  lines.push('');
  lines.push('| Assertion | Routing | Description |');
  lines.push('|---|---|---|');
  const sortedAssertions = [...ASSERTION_TYPES].sort((a, b) =>
    a.type.localeCompare(b.type)
  );
  for (const a of sortedAssertions) {
    lines.push(`| \`${a.type}\` | ${a.routing} | ${a.description} |`);
  }
  lines.push('');
  lines.push('### 5b. Canonical 100-prompt suite');
  lines.push('');
  lines.push(
    `Lives at \`${input.canonicalSuitePath}\`. Audited by ` +
      '`caia-aiml-architect eval-audit`. Coverage gate: ≥3 prompts per ' +
      'task category in `routing-config.ts`. Stale-baseline gate: 90 days.'
  );
  lines.push('');
  lines.push('## 6. Apprentice loop coordination');
  lines.push('');
  lines.push('Decisions in priority order:');
  lines.push('');
  lines.push('1. **Rollback**: ≥3 `RegressionDetected`/`DoDViolation` events in 24h → rollback.');
  lines.push('2. **Promote-canary**: candidate adapter passes win-rate threshold + zero forgetting flags.');
  lines.push('3. **Retrain**: ≥5 model-attributable failures in 7d window AND corpus snapshot stale.');
  lines.push('4. **Hold**: otherwise.');
  lines.push('');
  lines.push('## 7. Failure-mode taxonomy (Mentor events that are AI/ML-attributable)');
  lines.push('');
  lines.push('- `HallucinationFlagged` — counted in failure window.');
  lines.push('- `EvidenceGateFailure` — counted in failure window.');
  lines.push('- `RegressionDetected` — counted in failure window AND triggers rollback if blessed adapter.');
  lines.push('- `DoDViolation` — counted in failure window AND triggers rollback if blessed adapter.');
  lines.push('- `ToolMisuseFlagged` — counted in failure window.');
  lines.push('');
  lines.push('## 8. Cost discipline');
  lines.push('');
  lines.push(
    'Curator findings under category "Subscription & Resource Efficiency" with ' +
      'severity ≥medium feed into the architect\'s `coordinateApprenticeLoop()` ' +
      'verdict. They do not by themselves trigger retrain — they raise the ' +
      'priority of an already-warranted retrain.'
  );
  lines.push('');
  lines.push('## 9. Hardware budget');
  lines.push('');
  lines.push('| Hardware | Usable RAM (GB) for models |');
  lines.push('|---|---|');
  lines.push('| `mac-m1-pro-16gb` (default) | 11 |');
  lines.push('| `mac-m4-32gb` | 22 |');
  lines.push('| `cloud` | 64 |');
  lines.push('');
  lines.push("When a model's RAM exceeds the budget, the architect escalates to Claude.");
  lines.push('');
  lines.push('## 10. Re-evaluation triggers');
  lines.push('');
  lines.push('Re-open an AI/ML decision when any of these fire:');
  lines.push('');
  lines.push('- A new task category is added to `routing-config.ts` without a corresponding entry in the canonical suite.');
  lines.push('- An adapter passes the win-rate threshold but fails the forgetting check.');
  lines.push('- The convention doc auto-generation diverges across two consecutive runs (non-determinism bug).');
  lines.push('- DeepEval bridge becomes available for the orchestrator (subprocess install).');
  lines.push('- Operator hardware changes (CAIA_HARDWARE env var update).');
  lines.push('');
  lines.push('## See also');
  lines.push('');
  lines.push('- `agent/memory/architect_agents_directive.md` — the 12-architect campaign.');
  lines.push('- `agent/memory/agent_architecture_shape_2026-05-06.md` — Option E.');
  lines.push('- `agent/memory/apprentice_agent_directive.md` — the Apprentice loop this agent coordinates.');
  lines.push('- `packages/local-llm-router/README.md` — routing-config.ts source.');
  lines.push('- `packages/prompt-evals/README.md` — Promptfoo wrapper.');
  lines.push('- `packages/dspy-bridge/README.md` — DSPy bridge for compiled programs.');
  lines.push('- `packages/aiml-architect/DESIGN.md` — this agent\'s full design.');
  lines.push('');
  return lines.join('\n');
}
