/**
 * INDEX.md maintainer — keeps the per-directory INDEX files current
 * across decisions/, sign-offs/, and dialogues/.
 *
 * The decisions/INDEX.md is already maintained by ea-architect's
 * updateDecisionsIndex; this module adds the same discipline to the
 * sign-offs/ and dialogues/ directories which are new in this framework.
 */

import { join } from 'node:path';

import { defaultFsAdapter, type FsAdapter } from '@caia/ea-architect';

import type { IndexMaintenanceResult } from './types.js';

export interface SignoffIndexEntry {
  submissionId: string;
  verdict: string;
  planSlug: string;
  readTimeMinutes: number;
  signoffRelativePath: string;
  generatedAtIso: string;
}

export class IndexMaintainer {
  constructor(private readonly fs: FsAdapter = defaultFsAdapter) {}

  /**
   * Rebuild the sign-offs INDEX.md sorted reverse-chronologically.
   * Caller passes the full list of entries — IndexMaintainer is stateless.
   */
  rebuildSignoffsIndex(
    signoffsDir: string,
    entries: SignoffIndexEntry[]
  ): IndexMaintenanceResult {
    const sorted = [...entries].sort((a, b) => b.generatedAtIso.localeCompare(a.generatedAtIso));
    const path = join(signoffsDir, 'INDEX.md');
    const body = `# EA Sign-Offs — Index\n\nGenerated by @caia/ea-doc-steward. Sorted reverse-chronologically.\n\n| Generated | Plan | Verdict | Read time |\n|---|---|---|---|\n${sorted
      .map(
        (e) =>
          `| ${formatDate(e.generatedAtIso)} | [${e.planSlug}](${e.signoffRelativePath}) | ${e.verdict} | ${e.readTimeMinutes} min |`
      )
      .join('\n')}\n`;
    const prior = this.fs.exists(path) ? this.fs.readFile(path) : '';
    this.fs.writeFile(path, body);
    return {
      indexesUpdated: prior === body ? [] : [path],
      added: sorted.length,
      removed: 0
    };
  }

  /** Rebuild the dialogues INDEX with the listed submission ids. */
  rebuildDialoguesIndex(
    dialoguesDir: string,
    submissionIds: string[]
  ): IndexMaintenanceResult {
    const path = join(dialoguesDir, 'INDEX.md');
    const body = `# Defender Dialogue Logs — Index\n\nGenerated by @caia/ea-doc-steward. One file per submission.\n\n| Submission |\n|---|\n${submissionIds
      .map((id) => `| [${id}](${id}.jsonl) |`)
      .join('\n')}\n`;
    const prior = this.fs.exists(path) ? this.fs.readFile(path) : '';
    this.fs.writeFile(path, body);
    return {
      indexesUpdated: prior === body ? [] : [path],
      added: submissionIds.length,
      removed: 0
    };
  }
}

function formatDate(iso: string): string {
  return iso.slice(0, 10);
}
