name: Publish Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Configure Git
        run: |
          git config --global user.email "ci@caia.ai"
          git config --global user.name "CAIA CI Bot"
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Build all packages
        run: npm run build:all
      
      - name: Run tests
        run: npm run test:all
      
      - name: Version and publish changed packages
        run: |
          npx lerna version --yes --conventional-commits --create-release github
          npx lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}